### ISSUE TITLE
@Builder, generics and final fields

### ISSUE THREAD

**Issue by aroux** [peichhorn/lombok-pg#102]
Hi,

When I try to use the @Builder extension for this class :

```
@Builder
public class DomainContainer<D> {
    private final int a;
    private final D domain;
}
```

I got an error : _The type DomainContainer.ADef is not generic; it cannot be parameterized with arguments <D>_.

It seems that interfaces generated for non optional arguments are not always parameterized. If I remove one final (or both), it works.

Thank you,
Bests
Alexandre

**Comment by peichhorn** [comment]
Oh my, thanks for the report. Will fix it right away..

**Comment by peichhorn** [comment]
Done, I will probably release a new snapshot release tomorrow.

**Comment by aroux** [comment]
Ok thank you very much.
Bests
Alexandre
