### ISSUE TITLE
BeanInfo generation

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#104]
BeanInfo is used by many JavaBeans compliant applications - such as Netbeans GUI Editor - but the generation of the BeanInfo is sometimes ludicrous. Netbeans BeanInfo generation code is utter nonsense and is often 1,000 lines long even for simple objects. Clearly the whole BeanInfo concept would have been better achieved with annotations - but we're stuck with this awful legacy.

Often it is enough not to bother creating a BeanInfo at all and just go with introspection. However, sometimes a BeanInfo is needed just to set one or two properties, e.g. associated "description", "icon" or graphical properties.

I recently discovered that I need to provide about 20 lines of boilerplate with every Swing JComponent I (or you) write in order for the GUI Editor to work properly:

  http://netbeans.org/bugzilla/show_bug.cgi?id=215528

As far as I am aware, there is no existing auto-generation of BeanInfo classes with annotations. It seems like the perfect job for Lombok.

It would be great if in MyClass I could simply add an annotation which would generate a second BeanInfo class that looks something like this (plus extra features):

``` java
package uk.me.fommil;

import java.beans.BeanDescriptor;
import java.beans.SimpleBeanInfo;

/**
 * So that NetBeans doesn't try to set the LayoutManager.
 * 
 * @see <a href="http://netbeans.org/bugzilla/show_bug.cgi?id=215528">NetBeans #215528</a>
 * @author Samuel Halliday
 */
public class MyClassBeanInfo extends SimpleBeanInfo {

    @Override
    public BeanDescriptor getBeanDescriptor() {
        BeanDescriptor desc = new BeanDescriptor(MyClass.class);
        desc.setValue("isContainer", Boolean.FALSE);
        return desc;
    }
}
```

**Comment by fommil** [comment]
Some googling found this API, which looks exactly like I would have expected a Lombok API to look like: http://doc.formdev.com/jfd-annotations/com/jformdesigner/annotations/BeanInfo.html

But the whole framework is tied to a commercial product and not standalone.

**Comment by peichhorn** [comment]
Interesting idea, I will look into it.

**Comment by neg3ntropy** [comment]
using `@Value` object and swagger this has just hit me: no setters -> no properties -> no API documentation.
