### ISSUE TITLE
how to use lombok builder for subclasses

### ISSUE THREAD

**Issue by rvakkada** [peichhorn/lombok-pg#105]
Class A extends Class B with class A having a few fields and Class B addtional fields. How do I use the builder

**Comment by peichhorn** [comment]
Sadly this doesn't work for now. I still need to find a decent way to support this. If you already have ideas about this feature, please let me know.

I'll mark this issue as a duplicate of Issue #78, so please continue the discussion there.

**Comment by rvakkada** [comment]
Please do not use reflection

----- Original Message -----

**Comment by peichhorn** [comment]
I don't need to use reflection since I have all the info I need at compile time. I merely need to find a way to expose this feature to the user.

**Comment by rvakkada** [comment]
@peichhorn this comment was moved to the correct issue
