### ISSUE TITLE
Generate Javadoc

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#106]
It is often useful to create boilerplate Javadocs which simply contain the parameter names so that automated tools can have access to the parameter names (e.g. IDEs and non-bytecode implementations of Paranamer and netlib-java). It would be really cool if delombok automatically created Javadocs whenever they are missing. Personally I'd be happy with this happening by magic, but if it really has to be by an annotation, then on the class would be appropriate.

Of course, it would also be great if this worked on Lombok-generated methods as well ;-) And also pulling in some additional documentation from Javadocs that are sitting at some appropriate place (e.g. above a field which is marked with @Getter)

**Comment by peichhorn** [comment]
I have never tried out generating javadoc, so I need to create a small prototype first. After that we can iron out the details.

**Comment by nicholas22** [comment]
Yes this is a bit of a pain point of lombok (the core project) as well (see https://groups.google.com/forum/?fromgroups#!topic/project-lombok/m-6mhcXoVSk). They said they would implement it but I guess nobody got around implementing it.

**Comment by peichhorn** [comment]
Thanks for the link.. there are some decent design ideas in the discussion and the referenced issues. Once I get a prototype working the rest should be a walk in the park.

**Comment by nicholas22** [comment]
You, sir, are an optimist :)

**Comment by peichhorn** [comment]
Result of my quick experiment was, that adding Javadoc to javac is super easy, since you just have to specify the text-block.
Adding Javadoc to ecj is a lot harder. For now I only managed to get references working, that don't have any descriptive text. And Eclipse didn't show the Javadoc. But I've only started, so all in good times..

**Comment by fommil** [comment]
I only care about `javac` anyway, to hell with those non-reference compilers ;-)

BTW, does this leave an empty space between the javadoc and the method it's sitting on? A bit pedantic perhaps, but I'd like my generated code to not have the missing line.
