### ISSUE TITLE
ListenerSupport with generics

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#107]
Would it be possible to support a Listener<T> such as the following?

``` java
    public interface GenericListener<T> extends EventListener {

        public void listenToAdded(T added);

        public void listenToRemoved(T removed);

        public void listenToUpdated(T updated);
    }
```

I am unable to place such a listener in the @ListenerSupport list without getting "illegal start of expression" on character 40 of `@ListenerSupport(GenericListener<String>.class)`

**Comment by peichhorn** [comment]
> Would it be possible to support a Listener such as the following?

No, not really, since this is not valid java and touching the parser is a no-go.
The only way I could imagine it work, would be something like this:

`@ListenerSupport(type = GenericListener.class, typeArguments = String.class)`
or
`@ListenerSupport(type = GenericListener.class, typeArguments = {"SELF_TYPE", "EVENT_TYPE"})`

But then you won't be able to use `@ListenerSupport` with multiple listener types, so you would have to do something like this:

``` java
@ListenerSupport(types = {
  @GenericListener(type=GenericListenerA.class, typeArguments = {"SELF_TYPE", "EVENT_TYPE"}),
  @GenericListener(type=GenericListenerB.class, typeArguments = {"FOO_TYPE", "BAR_TYPE"})
})
```

If this is not too verbose.. then it's possible...

**Comment by fommil** [comment]
Hmm, I could live with that but one would have to be careful when implementing multiple versions of a generic listener if there are Collections in the parameters (e.g. if it were `Collection<T> added`) to avoid erasure issues (but that's a Java problem, not a Lombok problem).

If you add support for the @GenericListener, would it break the current notation? If so, then this RFE will have to be dropped because the current syntax is really good for most use cases.

**Comment by peichhorn** [comment]
> If you add support for the @GenericListener, would it break the current notation?

No, if `types`, or whatever I will call it, is optional the current notation would still work. Naturally using `value` and `types` together should result in an error.

a more complex example, but this gets unreadable pretty quick:

``` java
@ListenerSupport(genericTypes = {
  @GenericType(type=GenericListenerA.class, genericTypeArgs = {
    @GenericType(type=Collection.class, typeArgs = "T")})
  },
  @GenericType(type=GenericListenerB.class, typeArgs = {"FOO_TYPE", "BAR_TYPE"}),
})
```

**Comment by fommil** [comment]
OK, that would be quite nice! Would help reduce boilerplate in terms of having to create multiple Listeners which are essentially doing the same thing (perfect for atomic CRUD-like changes to @Data types).
