### ISSUE TITLE
Upgrading to 0.11.2 issue

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#111]
Internal compiler error: java.lang.ArrayIndexOutOfBoundsException: -2 at org.eclipse.jdt.internal.compiler.codegen.StackMapFrame.addStackItem(StackMapFrame.java:92)    Linq.java   /jpropel/src/propel/core/utils  line 0  Java Problem

This method is the culprit (used to compile under 0.10.0)

``` java
    @Validate
    @SuppressWarnings("unchecked")
    public static <T> Iterable<T> concat(@NotNull final Iterable<? extends T>... values)
    {
      ReifiedArray<? extends T> array = new ReifiedArray<T>(values);

      for (Iterable<? extends T> vals : array)
      {
        if (vals == null)
          throw new NullPointerException("Item of values");

        for (final T item : vals)
          yield(item);
      }
    }
```

**Comment by peichhorn** [comment]
I'm going to check it out. I'm sure you mean version 0.11.2. I think it's better if you would wait for 0.11.4 to come out, since 0.11.2 has an epic memleak that was plugged just 3 days ago. (memleak in lombok ^^)
If you want to try out some new stuff, I could easily release 0.11.3 just to get rid off the memleak.

**Comment by peichhorn** [comment]
Looking at this, I think this is definitely a position info bug. Not exactly sure what changed in lombok since I didn't touch anything in lombok-pg. But I will know more once I get home from work.

EDIT: No that wasn't it... must.... not... guess....

**Comment by peichhorn** [comment]
When I try the provided snipped (with the current HEAD I might add) , I get:

`Type mismatch: cannot convert from Iterator<capture#9-of ? extends T> to Iterator<T>`

`Type mismatch: cannot convert from element type capture#1-of ? extends T to Iterable<? extends T>`

`Type mismatch: cannot convert from Iterator<capture#5-of ? extends T> to Iterator<Iterable<? extends T>>`

These errors make sense, I'm not sure why you didn't see them earlier but I'm going to try out the provided example with 0.11.0 and 0.10.0 as well.

Here is the method, with the correct use of generic:

``` java
@Validate
@SuppressWarnings("unchecked")
public static <T> Iterable<T> concat(@NotNull final Iterable<? extends T>... values) {
  val array = new ReifiedArray<Iterable<T>>(values);

  for (val vals : array) {
    if (vals == null) throw new NullPointerException("Item of values");

    for (val item : vals) yield(item);
  }
}
```

EDIT: I've updated the error messages.. also used ReifiedArray of jpropel
EDIT: Updated example, you can even use val now..

**Comment by peichhorn** [comment]
The provided code did indeed work with lombok-pg 0.10.0 and 0.11.0 in both eclipse and javac.
In earlier version of yield there was a hard cast in yield, that was totally unnecessary, apparently this cast was hiding some major bugs. Sorry about that. I should really release 0.11.3..

**Comment by nicholas22** [comment]
Not your fault is it? :) 
(I thought yield is contributed)

**Comment by peichhorn** [comment]
> Not your fault is it? :) 
> (I thought yield is contributed)

I'm pretty sure, that I've messed it up..

**Comment by nicholas22** [comment]
Nothing to be sorry about! We're sticking with 0.11.0 for now. I think the thing that's going to force an upgrade is mixin support xD

**Comment by peichhorn** [comment]
na 0.11.3 is on the way (few hours to central sync though).. there are some major bugfixes since 0.11.0.. if you got some time please try out 0.11.3..

I really need to add a changelog xD
