### ISSUE TITLE
Memory usage of 0.11.2?

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#112]
I've been using 0.11.0 for a long time and memory was never an issue with Eclipse. I'm using 512MB of max heap (with typically ~80-200Mb being used by Eclipse). 

Playing around with 0.11.2 I'm getting OOM errors hitting 512MB every few minutes. I've come to the conclusion that it's the plugin, because reverting to 0.11.0 completely rectifies the issue...

**Comment by peichhorn** [comment]
See comment on issue #111...
There was a memleak in lombok that was fixed only 3 days ago.. I can easily release 0.11.3 if you like. Just let me know.

(Actually there where two memleaks, I fixed one and released lombok-pg 0.11.2 soon after, the other one slipped through my radar..)

**Comment by nicholas22** [comment]
Cheers

**Comment by peichhorn** [comment]
Does this mean, please release 0.11.3 ? xD

**Comment by nicholas22** [comment]
hehehe- well, if you have some time, it would be nice... ;)
