### ISSUE TITLE
@Builder needs to respect @Accessor

### ISSUE THREAD

**Issue by ribrewguy** [peichhorn/lombok-pg#113]
My company has a specific naming convention for member variables. @Accessor has helped greatly in producing correctly named getters, but the @Builder produces ugly methods. It would be great if @Builder removed the prefix specified by the @Accessor annotation.

**Comment by peichhorn** [comment]
Sure thing

**Comment by ribrewguy** [comment]
Thanks for the speedy attention to this issue!

**Comment by peichhorn** [comment]
Now `@Accessors` works perfectly with `@Builder` in both ecj and javac. Even the features `@EnumId`, `@LazyGetter`, `@BoundSetter` and `@FluentSetter` work with `@Accessors` in nearly all cases. There are still some scenarios where the use of `@Accessors` fails though. For example using `@EnumId`, `@NoArgsConstructor` and `@Accessors` together does not work as expected.

To fix this, I need to change how lombok is removing the annotations and import statements in javac.
I'll leave this issue open until then.

**Comment by peichhorn** [comment]
Done

**Comment by ribrewguy** [comment]
You rock!

**Comment by ribrewguy** [comment]
Is there a snapshot available? I don't see since 0.11.1.

**Comment by peichhorn** [comment]
There is a new 0.11.3 release available on maven central, [link](http://central.maven.org/maven2/com/github/peichhorn/lombok-pg/0.11.3/)

But this feature is not yet in the release, I have to deploy a  new snapshot. The snapshots are removed automatically once a proper release has been published, so all 0.11.3 snapshots are gone.

**Comment by ribrewguy** [comment]
Right. So I am wondering if you will be releasing any 0.11.4 snaps.

**Comment by peichhorn** [comment]
0.11.4-SNAPSHOT can be found here: [link](https://oss.sonatype.org/content/repositories/snapshots/)

**EDIT** Sorry the snapshot is not available yet, since I get Bad Request errors when deploying the artifact.. I need to investigate this once I get home from work.
**EDIT 2** Now the snapshot is available..

**Comment by ribrewguy** [comment]
Thanks! Was this issue addressed in this snapshot? I do not see the expected behavior.

**Comment by peichhorn** [comment]
It should be working with the snapshot.
For example, this works for me:

``` java
import lombok.Builder;
import lombok.Getter;
import lombok.experimental.Accessors;

public class BuilderResetExample {

    @Accessors(prefix="m_")
    @Builder
    @Getter
    public static class Person {
        private final String m_firstname;
        private final String m_name;
        private int m_age;
    }

    public static void main(String[] args) {
        Person.person().firstname("Chuck").name("Norris").age(72).build();
    }
}
```

If I've missed anything please let me know.
