### ISSUE TITLE
Support a compile time warning with @Warning

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#114]
I had the same idea as this chap

http://stackoverflow.com/questions/6889659

and it occurred to me that Lombok might be the place to implement such functionality.

For example, I might wish to mark a method with the following:

```
@Warning("See upstream issue #HHH-7476 for details")
public void read() {
         ...
}
```

and then I would expect to see a println from my compiler when I compile the class, something like

WARNING in path.to.MyClass.read: "See upstream issue #HHH-7476 for details"

**Comment by peichhorn** [comment]
How should the IDE behave? If it's OK, to see a warning there as well, it should be super easy. Otherwise I don't know how hard it's going to be.

**Comment by fommil** [comment]
I think optimally the IDE should show a warning when the method is used but - like @Deprecated - that might need to be supported in the IDE (e.g. with a NetBeans 'hint').

For the Lombok implementation, it would be good just to print it to the console on compile.

## 

Sam

**Comment by peichhorn** [comment]
Done. Both Netbeans IDE and Eclipse show the warning as well.
(it would have been a lot harder not to show a warning, that's why I asked)

example: `8:21 WARNING in method test.WarningPlain.read(): "See upstream issue #HHH-7476 for details"`

**Comment by fommil** [comment]
Awesome, thanks!

**Comment by peichhorn** [comment]
I've also created a wiki page for the feature.
Feel free to add anything to the page, if you think something is missing.

**Comment by fommil** [comment]
I'm not seeing the snapshots at https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/ to test this

**Comment by peichhorn** [comment]
Please use the 0.11.3 release available on maven central, [link](http://central.maven.org/maven2/com/github/peichhorn/lombok-pg/0.11.3/)

EDIT: Sorry this feature is not in the release.. I have to deploy a new snapshot then.. 
BTW the snapshots are removed automatically once a proper release has been published.

**Comment by silviuburceadev** [comment]
I haven't tried it yet, so please don't be mad if i ask an obvious question:
Can you suppress this warning? I think that you can't at the moment because a warning type is missing.
