### ISSUE TITLE
For loop Yield problem

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#12]
I'm getting some strange error messages when trying to implement the following snippet:

```
public static <T> Iterable<T> skip(@NotNull final Iterable<T> values, final int count)
{
    int i = 0;
    for(T item : values)
    {
        if(i++ < count)
            continue;

        yield(item);
    }
}
```

**Comment by nicholas22** [comment]
Worked around it using something like this:

```
    Iterator<T> iterator = values.iterator();
    for(T item : values)
      if(iterator.hasNext())
        iterator.next();

    while(iterator.hasNext())
      yield(iterator.next());
```

**Comment by peichhorn** [comment]
Yeah when I try it out I get " The literal -1 of type int is out of range". The reason for this is, that yield gets transformed to an anonymous iterator containing a state-machine.
See the example: http://peichhorn.github.com/lombok-pg/Yield.html
Now the case pattern is initially "-1" and gets replaced by the actual state number later. So this mechanism is somehow broken for your example, I will look into it.

**Comment by nicholas22** [comment]
I've got a similar one for when you're looking this stuff:

```
for(TSource item : values)
    {
        try
        {
            TDest temp = destinationClass.cast(item);
            yield(temp);
        }
        catch(ClassCastException e)
        {
            continue;
        }
    }
```

Workaround:

```
    for(TSource item : values)
    {
      TDest temp = null;
        try
        {
            temp = destinationClass.cast(item);
        }
        catch(ClassCastException e)
        {
        }

           yield(temp);
    }
```

**Comment by peichhorn** [comment]
Should work now, I will upload a new edge release tomorrow.
If it still doesn't work reopen this issue.
