### ISSUE TITLE
Source generation working for all features

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#128]
I thought there was an issue for this already.

I noticed that some annotations are not being converted when used with the delombok maven plugin: can you please make sure that delombok works with all the annotations. If memory serves, the bound property and listener annotations were not generating source code.

**Comment by nicholas22** [comment]
Please contribute and this will be merged

**Comment by fommil** [comment]
I'm currently working with Scala and probably not back to Java for – hopefully – a long while, sorry.
