### ISSUE TITLE
Inclusion in main Lombok

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#134]
there are some features of Lombok-PG which are just amazing and should be brought in by the main Lombok team, e.g. ListenerSupport, BoundPropertySupport, what is the process to get them included?

**Comment by nicholas22** [comment]
Bring them to the attention of the lombok authors as a first step.

**Comment by fommil** [comment]
@nicholas22 I already did on the mailing list and there was no uptake.

In particular, the support for listeners is top of my list.
