### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by ribrewguy** [peichhorn/lombok-pg#135]
There hasn't been any code changes in 5 months. Has this project been abandoned?

**Comment by nicholas22** [comment]
Yes no recent updates- but this is a fork of the main lombok, which is fed the latest features. Some of them will be under an "experimental" package, but eventually merge in the same package names as this project. See lombok for more info.

**Comment by ribrewguy** [comment]
So, yes this project has been abandoned? Next to none of these features have made it into lombok yet. So it seems there are at least a handful of people that rely on the features introduced in lombok pg that are out of luck. It would be unfortunate to see this project die as I cannot imagine these features will make it into lombok any time soon.

**Comment by bennid** [comment]
I’m with Todd on this one.  We use some of the features here that aren’t in Lombok main yet.

-Ben
