### ISSUE TITLE
@Data(callSuper=true) constructor

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#14]
Could the @Data(callSuper=true) also call the superconstructor?
@Data generates, I believe, an all args constructor, so it would be natural to do so for the subclass, calling the super constructor too in the beginning of the newer constructor, I should think.

Example:

@Data
class A {
private final String a;
}

class B {
private final String b;
}

// we should be able to do
A a = new A(a);
B b =new B(a, b);

Which means B() called A(a) then set: this.b = b;

You have mentioned this beforehand and I also got interest for this from another dev. team for this, so I'm creating an issue for it.

**Comment by peichhorn** [comment]
> @DaTa generates, I believe, an all args constructor, so

No `@Data` uses `@RequiredArgsConstructor`, but I will have to make changes to `@AllArgsConstructor`, `@RequiredArgsConstructor` and `@NoArgsConstructor` where:
- `@RequiredArgsConstructor(callSuper=true)` means: create constructor for each super constructor and all my non-initialized final fields
- `@AllArgsConstructor(callSuper=true)`  means: create constructor for each super constructor and all my fields
- `@NoArgsConstructor(callSuper=true)`  means: create constructor for each super constructor

small example:

```
@AllArgsConstructor
@NoArgsConstructor
public class A {
  private String a;
  private int b;
}

@AllArgsConstructor(callSuper=true)
@NoArgsConstructor(callSuper=true)
public class B extends A  {
  private float c;
}

// lombokized B
public class B extends A {
  private float c;

  public B() {
    super();
  }

  public B(final float c) {
    super();
    this.c = c;
  }

   public B(final String a, final int b) {
      super(a, b);
   }

   public B(final String a, final int b, final float c) {
      super(a, b);
      this.c = c;
   }
}
```

Hopefully I didn't miss anything in the example. ;)

**Comment by nicholas22** [comment]
Just wondering how's the progress on this long standing issue xD

**Comment by peichhorn** [comment]
Essentially it works, except for inner classes.

**Comment by nicholas22** [comment]
Confirming that it works on non-inner classes on my end.

**Comment by peichhorn** [comment]
Sorry to disappoint you, but constructor does not call the super constructor yet. (meaning the 0.10.2-EDGE release)
Since I didn't merge my local branch yet. So it shouldn't work right now.
Good news is, guess what I'm working on right now? ;)

**Comment by nicholas22** [comment]
Uhm, I must making incorrect assumptions then, will look into it a bit more...

**Comment by rolfw** [comment]
@peichhorn, I'm also interested in this feature. Your post suggests it's ready but not available for download yet. I've checked 0.10.8 and also cloned the master branch, just to be sure, but calling all super constructors is not there.

Can you share the code/jar? It would be a big time saver for me

**Comment by peichhorn** [comment]
I've not pushed the changes yet, since there still was a minor issue with inner classes, that I wanted to investigate first. But I'm working on it.

**Comment by rolfw** [comment]
Thanks, I'll keep an eye out. Do you have a timeline in mind?

On 14 April 2012 10:17, Philipp Eichhorn <
reply@reply.github.com

**Comment by peichhorn** [comment]
I'm aiming for this weekend, but no promises.

**Comment by rolfw** [comment]
Thanks Philipp, that would be awesome! Also, not expecting any :)

On Thursday, April 19, 2012, Philipp Eichhorn <
reply@reply.github.com>
wrote:

**Comment by peichhorn** [comment]
Added `@Data(callSuper=true)` on this branch:
https://github.com/peichhorn/lombok/tree/Issue_19_@Data_needs_a_callSuper

So lombok-pg 0.11.0 will contain this feature.

**Comment by rolfw** [comment]
Great! I'll check it out..

**Comment by nicholas22** [comment]
Many thanks!

**Comment by rolfw** [comment]
Working fine, thanks again!
