### ISSUE TITLE
lombok-pg does not work with Java  8

### ISSUE THREAD

**Issue by teras** [peichhorn/lombok-pg#146]
This probelm seems to be fixed in official Lombok distribution, since there are some bug reports about it
https://code.google.com/p/projectlombok/issues/detail?id=451
and 
https://code.google.com/p/projectlombok/issues/detail?id=591

Probably a new lombok-pg version should be produced?

Thanks!

**Comment by hprobst** [comment]
Hi Philipp, 
do you plan to support Java 8 / latest lombok version 1.12.6 or higher in the next weeks/months?
Best regards,
Hardi

**Comment by hprobst** [comment]
FYI: I created a fork of lombok to support bound setters with Java 8 - have a look at:

https://code.google.com/p/projectlombok/issues/detail?id=321
