### ISSUE TITLE
Improvement to @NotNull error message

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#15]
The @NotNull validation error message is a bit vague, so you have a function with like (say) 10 arguments and whichever one fails throws an "IllegalArgumentException: The validated object is null."

Firstly I wonder if it would be possible to throw a NullPointerException instead? It is after all a null reference and people expect that as an exception. This is only for @NotNull, the other @Validate correctly in my opinion don't do that. And secondly would it be possible to include the argument name or if that's not discoverable, perhaps its index e.g. #1, #2...#n? In other words: "NullPointerException: The argument in position 1 is null" or something along these lines...

**Comment by peichhorn** [comment]
Expecting an NPE or an IAE depends largely on your taste and on the code you have worked with.
The current implementation behaves like org.apache.commons.lang.Validate.notNull(Object object).
And what you suggest looks a lot like the null-check I know from intellij IDEA.
I with defiantly improve the exception message so that it includes the argument index. When it comes to
throwing an NPE instead of an IAE, I really need to look at other more widely used frameworks and see what
they do.

**Comment by peichhorn** [comment]
After a small google session I pretty much got nowhere. I noticed that google guava uses NullPointerExceptions in these cases. Josh Bloch recommends to throw NullPointerExceptions. After reading the javadoc of NullPointerException it sounds acceptable to throw an NPE.
Still there are two camps, the ones that prefer a NullPointerException and the ones that like a IllegalArgumentException.
For now you can count me to the second camp, that does not mean I am opposed to throwing a NullPointerException. I prefer to throw an IAE simply for the fact that is raises the severity of each NPE you still get.

**Comment by nicholas22** [comment]
Wow, nice research there :)

My opinion was just based on gut feel and a bit of feedback from others. Having read all this I think there should be an NPE thrown for @NotNull, because it is like a special case of invalid argument, which would be nice to signify in a strongly typed manner, with this special exception describing it. The InvalidArgumentException could still be there for when e.g. a value is larger than expected (@With). But it's up to you, as ever.
