### ISSUE TITLE
How to deal with checked Exceptions in @Function and @Action

### ISSUE THREAD

**Issue by peichhorn** [peichhorn/lombok-pg#16]
For now it is not possible to throw checked Exceptions inside a method annotated with `@Function`.
The known workaround for this issue is the usage of @SneakyThrows.

One way to support checked Exceptions would be to copy list of thrown Exceptions to the 'apply' method.
But for this to work we need to change the interface signature like this:
`public R apply(T1 t1, T2 t2, ..., TN tn) throws Exception;`
with the issue now being that I have to handle the Exception everywhere I use 'apply'.

So how to deal with checked exceptions?

**Comment by nicholas22** [comment]
In my opinion it's better to use SneakyThrows for the (few) times you need them than to force Exceptions everywhere... Will need to ponder a bit more.

**Comment by peichhorn** [comment]
Yeah let's stick to `@SneakyThrows`.
