### ISSUE TITLE
@ExtensionMethod bug

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#18]
1) Once a method is used, chaining further methods (in a fluent API style) does not give you code completion.
You can continue chaining things, but you need to remember the API to do e.g:

names.map(toUpperCase()).filter(isNotNullOrEmpty()).etc.etc.

2) Would it be possible to have the compiler warn you when you're forgetting to pass arguments to methods? e.g:
names.filter(); // compiles but throws verifyError at runtime, because filter expects a function argument

Thankfully when you chain more than one call forgetting parameters: 
names.map().filter(); // does not compile

It says:
Internal compiler error: java.lang.NullPointerException at org.eclipse.jdt.internal.compiler.ast.MessageSend.analyseCode(MessageSend.java:60)

**Comment by peichhorn** [comment]
This won't be so easy as the other issues I fixed today, but I'm on it.

**Comment by peichhorn** [comment]
OK now you get a halfway decent compile error, example:
`String s = foo.orElse();`
generates:
`The method orElse(T, T) in the type Objects is not applicable for the arguments (String)`

Is this message acceptable?

**Comment by nicholas22** [comment]
Sure, anything is better than runtime exception :)
