### ISSUE TITLE
@Validate on constructor

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#19]
Using @Validate and @NotNull in e.g. a single arg constructor. If the constructor has to call super (in its first line of code of course) there is a problem with javac/Ant due to first call not being to super constructor! This is not a problem with eclipse though. My suggestion (which is not ideal) is that for javac a check could be made to emit the code after the call to the super constructor.

**Comment by peichhorn** [comment]
Will do thx
