### ISSUE TITLE
Functional feature request

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#2]
In your experience, how hard would it be to create a method annotation that wraps said method within a specific anonymous class?

I am using a LINQ re-implementation for Java (that I wrote, link: https://github.com/nicholas22/jpropel/blob/master/src/propel/core/utils/Linq.java#L2519) and I think this would make the use of most things like selectors and filters much more concise. 

So this annotation would hide the annotated method (e.g. rename it, perhaps with synthetic semantics) and replace it with another method that creates an anonymous class, let's call it for example FunctionWithOneArgument&lt;TResult, T&gt; where type parameter TResult is the function result and T is the argument.

That would allow one to use:
Linq.select(people, nameSelector)

...if given the following function...
@FunctionWithOneArgument
String nameSelector(Person person) { return person.getName(); }

...instead of e.g.
Linq.select(people, new FunctionWithOneArgument<String, Person>() {
   String operateOn(Person person) {
      return person.getName();
   }
});

This is because it would wrap the anonymous class creation in a method within the code. Currently this has to be done manually for any code that accepts a "function", but this process could be automated, plus there would be no need for all this boilerplate.

If this would be possible I could then re-write portions of the LINQ library with support for this and in combination to your extension method annotation and yield operator this would bring a lot of the functional programming stuff of .NET to Java, much before Java 8...

**Comment by peichhorn** [comment]
Once we nail down how this annotation should work, it's pretty straight forward.

Let's say we go for the annotation @Function and we simply count the method parameter to find out which version of FunctionWithXXXXArgumentX to use.
I'm not quite sure how FunctionWithOneArgument or even FunctionWithTwoArguments (let's assume they are interfaces) come into play, does the lombok user provide them? And if so, how?
Lombok is not supposed to be a runtime dependency so they definitely wont be defined as API in there.
Let me sleep on it, maybe i get more ideas.

**Comment by nicholas22** [comment]
Using @Function as you suggest is even better from an end-user perspective. There could also be @Action, for methods rather than functions. The implementation could easily identify the number and class type of arguments via reflection.

As for the interfaces, they could be part of lombok, can't we use de-lombok for this purpose? Another approach would be for lombok to generate them somewhere in application scope, or even ask the user to provide them while checking the signatures match. Proxying could also work, dispatching method calls to certain other, configurable, methods. 

In any case, they could look something like this:

public interface FunctionWithOneArgument&lt;T, TResult&gt; {
&nbsp;&nbsp;&nbsp;TResult operateOn(T arg);
}

public interface FunctionWithTwoArguments&lt;T1, T2, TResult&gt; {
&nbsp;&nbsp;&nbsp;TResult operateOn(T1 arg1, T2 arg2);
}

I think this is the convention used for C# Function delegates. I mixed up the order of type parameters in my earlier comment.

**Comment by peichhorn** [comment]
Just a quick feedback, I'm already playing around with this stuff, but it may take a while until I'm satisfied.

**Comment by nicholas22** [comment]
Nice :) That's great news! Feel free to use me as a tester.

**Comment by nicholas22** [comment]
bump!

**Comment by peichhorn** [comment]
Just updated the [lombok-pg-0.10.0.jar](http://cloud.github.com/downloads/peichhorn/lombok-pg/lombok-pg-0.10.0.jar), which supports @Function. If you don't configure it otherwise you will have to add [lombok-pg-runtime-0.10.0.jar](http://cloud.github.com/downloads/peichhorn/lombok-pg/lombok-pg-runtime-0.10.0.jar) as a runtime dependency since it contains the function interfaces.

A small example:

```
import lombok.Functions.Function1;
import lombok.Function
...
@Function
public static <T> void notNull(T object, Function1<T, Void> notNullFunction) {
  if (object != null) notNullFunction.apply(object);
}
...
```

gets transformed to:

```
import lombok.Functions.Function1;
...
public static <T>lombok.Functions.Function2<T, Function1<T, Void>, java.lang.Void> notNull() {
  return new lombok.Functions.Function2<T, Function1<T, Void>, java.lang.Void>() {
    public java.lang.Void apply(final T object, final Function1<T, Void> notNullFunction) {
      if (object != null) notNullFunction.apply(object);
      return null;
    }
  };
}
...
```

If you want to use other or your own interfaces as Function templates you can do this `@Function(template=MyFunctionTemplate.class)`.
Then the annotation-handler will look at the given class and all accessible member-classes for classes that satisfy the following criteria: (basically what we talked about above)
- they are public interfaces
- they only have one method
- the TypeArguments of the interface and the method matches like this: 

```
public interface AnyFunctionName<T1, T2, ..., TN, R> {
    R anyMethodName(T1 arg1, T2 arg2, ..., TN argN);
 }
```

This is the default template definition to get a feeling how it's supposed to look like: [Functions.java](https://raw.github.com/peichhorn/lombok-pg/master/src/core/lombok/Functions.java)

Please note that there are still some issues, for example I have an issue with the auto-completion and I'm not sure I like the annotation method name, but stuff like this has to wait a bit, since I won't have much time in the next few weeks.

**Comment by nicholas22** [comment]
Holy crap! This is very nice work indeed! :D 

Yes, the only problem is the auto-completion in eclipse. It happens when lombok.Function is imported.
But it otherwise works as expected. I am so enthralled by this! I'm doing a presentation about Scala for a fairly large audience and I want to suggest that lombok-pg's functional stuff as a nice alternative if people don't want or can't use Scala for projects. It's so close...! Is there any chance you can fix the auto-completion bug? Hopefully you can find a bit of time to have a look at this. 

Here is the problem stacktrace:
!SESSION 2011-09-20 19:17:50.985 -----------------------------------------------
eclipse.buildId=I20110613-1736  
java.version=1.6.0_26  
java.vendor=Sun Microsystems Inc.  
BootLoader constants: OS=linux, ARCH=x86, WS=gtk, NL=en_GB  
Framework arguments:  -product org.eclipse.epp.package.java.product  
Command-line arguments:  -os linux -ws gtk -arch x86 -product org.eclipse.epp.package.java.pr
oduct                                                                                        

!ENTRY org.eclipse.jdt.ui 2 0 2011-09-20 19:18:48.567
!MESSAGE The 'org.eclipse.jdt.ui.JavaAllCompletionProposalComputer' proposal computer from th
e 'org.eclipse.jdt.ui' plug-in did not complete normally. The extension has thrown a runtime 
exception.  
!STACK 0  
java.lang.ClassCastException: org.eclipse.jdt.internal.codeassist.CompletionEngine cannot be 
cast to org.eclipse.jdt.internal.compiler.Compiler  
        at lombok.eclipse.agent.Patches.completeNode(Patches.java:110)  
        at lombok.eclipse.agent.PatchFunction.onClassScope_buildFieldsAndMethods(PatchFunctio
n.java:59)  
        at org.eclipse.jdt.internal.compiler.lookup.ClassScope.buildFieldsAndMethods(ClassSco
pe.java)  
        at org.eclipse.jdt.internal.compiler.lookup.CompilationUnitScope.buildFieldsAndMethod
s(CompilationUnitScope.java:64)  
        at org.eclipse.jdt.internal.compiler.lookup.LookupEnvironment.completeTypeBindings(Lo
okupEnvironment.java:267)  
        at org.eclipse.jdt.internal.codeassist.CompletionEngine.complete(CompletionEngine.jav
a:1851)  
        at org.eclipse.jdt.internal.core.Openable.codeComplete(Openable.java:130)  
        at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:35
7)  
        at org.eclipse.jdt.internal.core.CompilationUnit.codeComplete(CompilationUnit.java:34
5)  
        at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.internalCompu
teCompletionProposals(JavaCompletionProposalComputer.java:244)  
        at org.eclipse.jdt.internal.ui.text.java.JavaCompletionProposalComputer.computeComple
tionProposals(JavaCompletionProposalComputer.java:206)  
        at org.eclipse.jdt.internal.ui.text.java.JavaTypeCompletionProposalComputer.computeCo
mpletionProposals(JavaTypeCompletionProposalComputer.java:61)  
        at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.compute
CompletionProposals(CompletionProposalComputerDescriptor.java:318)  
        at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletion
Proposals(CompletionProposalCategory.java:267)  
        at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(Cont
entAssistProcessor.java:283)  
        at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProp
osals(ContentAssistProcessor.java:243)  
        at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(C
ontentAssistant.java:1830)  
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(Comp
letionProposalPopup.java:556)  
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionP
roposalPopup.java:553)  
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionPropo
salPopup.java:488)  
        at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)  
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(Complet
ionProposalPopup.java:482)  
        at org.eclipse.jface.text.contentassist.ContentAssistant$2.run(ContentAssistant.java:
377)  
        at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:35)  
        at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:135)
        at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:3563)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3212)
        at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
        at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
        at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
        at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
        at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
        at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
        at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:1
23)
        at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(Eclips
eAppLauncher.java:110)
        at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLaunc
her.java:79)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
        at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:
25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
        at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
        at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
        at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

**Comment by peichhorn** [comment]
One thing I'm going to add to `@Function` before I close this issue is this:
Any parameter that starts with "_" will work as a constructor argument for the anonymous function class.
What do you think about that?

Of cause I will tackle the Auto-Completion bug as soon as I can.

**Comment by nicholas22** [comment]
As a convention, the underscore prefixing is predominantly used in Microsoft environments so it sounds like a good choice to me.

**Comment by peichhorn** [comment]
Quick update:
- the CCE in the Auto-Completion is no longer.
- parameters whose names start with an underscore will not be used as function parameters but rather handled as fixed values for every execution of the function.

If there is still something missing, please let  me now.

**Comment by peichhorn** [comment]
damn I found a small issue, eclipse complains about this:

```
@Function
public static void justThrowAnException() {
  throws new RuntimeException();
}
```

cause it stands for this:

```
@Function
public static Function0<Void> justThrowAnException() {
  return new Function0<Void> {
    public Void apply() {
      throws new RuntimeException();
      return null;
    }
  };
}
```

and as you can see the return statement can never be reached, so eclipse brags on about it.

Edit by nicholas22: You can work around it if you declare "justThrowAnException" with Void, instead of void!

**Comment by nicholas22** [comment]
wow this works VERY nicely. Will try out some more Functions. I'm already thinking about migrating all the functional stuff I have written to this, the syntax is so ...sugary!

**Comment by nicholas22** [comment]
For some reason the @Function doesn't work well in Netbeans. Do I have to do some kind of installation, like I had to do in Eclipse? It's my first time using lombok in Netbeans. Simples stuff like getters and setters seem to work... Here is what I'm doing:

public static void main(String[] args) {
&nbsp;&nbsp;&nbsp;String[] names = new String[] { "abc" };  
&nbsp;&nbsp;&nbsp;select(names, toUpperCase());
}

@Function
public static String toUpperCase(String arg) {
&nbsp;&nbsp;&nbsp;return arg.toUpperCase();
}

public static &lt;TSource, TResult&gt; TResult[] select(TSource[] values, Function1&lt;TSource, TResult&gt; selector)
{  
&nbsp;&nbsp;&nbsp;List&lt;TResult&gt; result = new ArrayList&lt;TResult&gt;(values.length);

&nbsp;&nbsp;&nbsp;for(TSource item : values)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;result.add(selector.apply(item));

&nbsp;&nbsp;&nbsp;return null;
}

**Comment by peichhorn** [comment]
No, for now I don't patch anything in netbeans.

**Comment by nicholas22** [comment]
Sorry I didn't understand what you mean, do you mean you don't port this patch to Netbeans yet? I didn't realise it's a two-phase thing what you have to do...

**Comment by peichhorn** [comment]
Ah sorry let me explain real quick. Basically lombok supports the Java Compiler (javac) and the Eclipse Compiler (ecj). And for now all the features have to be implemented in both worlds, because these compilers work rather different. To support some advanced features in eclipse lombok and lombok-pg have to perform some nasty tricks. I find that a lot of stuff is easier add to javac (which in return is used by Ant, Maven and what not). The additions to the eclipse compiler allows us support for gwt, play, some other stuff and well, eclipse.
Since Netbeans uses javac the features should work/compile too but some advanced IDE features are still broken. This doesn't mean that everything is charming in eclipse-land either. A lot of the refactor-operations are still broken in eclipse.

**Comment by nicholas22** [comment]
You're doing a great job, it's not 100% bug free, but what software really is?

**Comment by nicholas22** [comment]
Hi Philipp,

Just stumbled upon a tricky one ;)
I was trying to do this:

@Validate
    public static &lt;T&gt; List&lt;T&gt;[] test(@NotNull final T[] values, @NotNull final T delimiter)
    {
        List&lt;List&lt;T&gt;&gt; parts = new ArrayList&lt;List&lt;T&gt;&gt;();
        return where(parts, elementsExist()).toArray(); // imagine toArray exists here...
    }

```
@Function
private static Boolean elementsExist(List<T> list){
return list.size() > 0;
}
```

  @Validate
    public static &lt;T&gt; Iterable&lt;T&gt; where(@NotNull final Iterable&lt;T&gt; values, @NotNull final Function1&lt;? super T, Boolean&gt; predicate)
    {
        List&lt;T&gt; result = new ArrayList&lt;T&gt;(DEFAULT_LIST_SIZE);

```
    for(T element : values)
        if(predicate.apply(element))
            yield(element);
}
```

The workaround is to use a raw type in elementsExist(List list) instead of the generic list...

**Comment by nicholas22** [comment]
I think it would be sweet if we could take advantage of the extra run-time information that functions have because they are implemented using anonymous classes. As you know, when using anonymous classes in Java you can detect the actual type parameters used. This is not possible with concrete classes due to type erasure. The advantage of knowing the run-time type is _huge_ when dealing with e.g. generic collections classes, generic methods and the like. Here are two suggestions on how to do that:

1) Make Function0, Function1, etc. abstract classes and in the constructor capture the generic return type and generic arguments. I can give you copyright of the SuperTypeToken implementation (1 class) which I have taken and you can distribute this with lombok-pg-runtime perhaps. But its simple enough you can find how to do this onlune. Either way, if you store this information in final fields within Function0, Function1, etc. and allow for getters to access these, code that uses these classes can know what types its working with at any point.

2) Another approach is to continue using interfaces Function0, Function1, etc. but expand them with getters which return the aforementioned run-time type parameter information. I'm not sure you can have fields with this approach, so the getters would actually poll the run-time info on demand. These would need to be implemented when you wrap the method, again using a super type token polling mechanism.

What are your thoughts on the matter?

**Comment by nicholas22** [comment]
Just ran into a case where I'm limited without this:

```
@Validate
public static <TFirst, TSecond, TResult> TResult[] zip(@NotNull final TFirst[] first, @NotNull final TSecond[] second, @NotNull final Function2<TFirst, TSecond, TResult> function)
{
    List<TResult> result = new ArrayList<TResult>(DEFAULT_LIST_SIZE);

    int count = Math.min(first.length, second.length);

    for(int i = 0; i < count; i++)
        result.add(function.apply(first[i], second[i]));

    return toArray(result, function.getGenericReturnTypeParameter()); // <-- need type info here
}
```

As you can see TResult cannot be inferred without some type passing mechanism...

**Comment by nicholas22** [comment]
To clarify that last line, I'm trying to something like this:

return result.toArray((TResult[])Array.newInstance(function.getReturnTypeParameter(), length));

This is because you can't do TResult.class, or new TResult[], etc. due to limitations. Hence why I need the type to be detected (which can be done upon the function instantiation)

**Comment by peichhorn** [comment]
Yup I totally see the need. I just need to collect my thoughts on that and then I will let you know my ideas.

**Comment by nicholas22** [comment]
Hehe sry ;) wrote a few posts in a matter of minutes, not trying to bombard you or anything, just a bit excited with this! :)

**Comment by nicholas22** [comment]
Another one to mull over is whether it's worth detecting Boolean return types and potentially using the value type boolean instead of Boolean to avoid boxing/unboxing and unnecessary heap allocations, as there may be a lot of functions that simply act as predicates:

static &lt;T&gt; boolean isNotNull(T item)
{
&nbsp;return item != null;
}

**Comment by nicholas22** [comment]
Hi Philipp, just wondering if you've had some preliminary thoughts on how to go with the design of this. The reason I'm asking is that I have time today (Sunday) to do some more porting work but I'm getting to the point where I need to decide whether to mock that there is support on the interface(s) or do I take another route with methods that require type information.

**Comment by peichhorn** [comment]
I would go with you second suggestion so adding the getter methods to the interface and poll the run-time info on demand, as I like to think of it as an advanced use case, that one doesn't have to do that often.

>  I'm not sure you can have fields with this approach

Yeah you could and use an initializer block to initialize them, like this:

```
private final Class<?> clazz;
{
  clazz = workYourMagic(getClass());
}
```

But back to the real problem.
The part where I'm currently stuck right now is how to work this stuff in the function-template mechanism. And how should the methods look like.

```
Class<?> getReturnType();

Class<?> getParameterType1();
...
Class<?> getParameterTypeN();
```

or just

```
Class<?> getReturnType()

Class<?> getParameterType(int parameter index);
```

Do you even need the parameter-types or is the return-type enough? Because I only stumbled over use-cases where the return-type would suffice.

**Comment by nicholas22** [comment]
The return type is enough for some simple/common use cases, like e.g. the zip() one I mentioned above, or mapping/filtering, but when using more advanced stuff, e.g. function composition and monads, it would become necessary to pass argument type information, if for example you're instantiating/returning an array, as the argument type basically is used as the return type.

Both approaches you have suggested above would work, with the first one being more strongly typed in my opinion, but having the second approach would also be more than enough.

**Comment by peichhorn** [comment]
Ok the first one it is. I will add the getters for the type info asap, although I'm crying a little bit inside right now. xD

As for the predicate problem, I think I can live with the boxing and unboxing simply because I wouldn't use the @Function stuff in real performance critical situations.

**Comment by nicholas22** [comment]
That's very helpful. Don't feel bad, you have just enabled higher order functional compositions ;D

As for the functional performance I wouldn't be very dismissive of your work myself, I've been looking closely at reverse engineered Scala code and the basis of their functional features are ...anonymous classes, which is what we have here! :) 

Benchmarks show that performance-wise Scala is on par with Java. A lot of this stuff can be optimised by HotSpot as well, but I still think it is a good idea to avoid heap allocations for predicates (by using primitive types), please consider it as a v. low priority thing...
If you don't want to complicate your @Function logic, maybe there could be a @Predicate annotation.

**Comment by nicholas22** [comment]
Just a question about using @Function with closures, is it at the moment possible to pass arguments to the generated functions?

**Comment by peichhorn** [comment]
do you mean something like this:

```
@Function
public boolean endsWith(final String string, final String _prefix) {
  return string.endsWith(_prefix);
}

public Function1<String, Boolean> endsWith(final String _prefix) {
  return new Function1<String, Boolean>() {
    public Boolean apply(String string) {
      string.endsWith(_prefix);
    }
  };
}
```

Or do you want to change `_prefix` from time to time, because this does not work for now?

**Comment by nicholas22** [comment]
No what you showed is exactly what I mean. So we have closure support ;)
I didn't realize this was already included on the version I'm using.

Mutating the _prefix is not allowed by the compiler, in fact it has to be declared as final, but this as you know can be easily circumvented by a wrapper containing the _prefix object, which would be passed instead of the _prefix object itself. So I wouldn't bother with the latter scenario.

**Comment by nicholas22** [comment]
I'm getting a minor bug, when a type is unused in a file and you use it within a @Function block, the Eclipse IDE Ctrl-Shift-O (auto-import) does not discover it. In fact, if you have imported it and do auto-import as above, it is actually removed from imports!!! Workaround at the moment is to not use Ctrl+Shift+O...

Edit: Another minor bug, you can't throw checked exceptions within @Function blocks, workaround: use @SneakyThrows with @Function. To fix this, the generated function could probably read which checked exceptions are found in the signature of the original function and include them in the generated one.

**Comment by peichhorn** [comment]
Thx, I will fix the exception handling for checked exceptions.

The auto-import is a whole different story and extremely hard to fix.

**Comment by nicholas22** [comment]
Hmm, I was afraid this would be the case. I'm hoping that looking at how it's done in constructs such as @SneakyThrows (where essentially the code is again wrapped into something else) could yield some ideas on how to tackle this, as it could be a pain in the long term.

**Comment by peichhorn** [comment]
I totally forgot about the "fixed" position info in @SneakyThrows, @CleanUp and @Synchronized.
So it might be doable, but I'm sure it will break other minor eclipse features. I guess this is something I just have to try out.

**Comment by nicholas22** [comment]
Just came across a case where @Action would be nice to have: A method accepts a Function1&lt;T, Void&gt; and its overloaded version accepts Function1&lt;T, TResult&gt; (i.e. when you have a case where the function returns something and another does not return anything (void)) the type erasure of these two methods is the same, so you must rename the method instead of overloading.

**Comment by peichhorn** [comment]
So you want something like this:

```
public interface Action1<T1> {
  void apply(T1 t1);
}

public static <T> void andThen(T value, Action1<T> action) {
  if (value != null) action.apply(value);
}

public static <T, R> R andThen(T value, Function1<T, R> function) {
  return value == null ? null : function.apply(value);
}
```

Once I'm done with @Function @Action should be done in no-time.

**Comment by peichhorn** [comment]
I've added support for `@Action` and type getters, so I will close this issue.
If you stumble over anything please create a new issue instead of reopening this one.

**Comment by nicholas22** [comment]
I forgot to add to this: Thank you so much! :)
