### ISSUE TITLE
@Function (still) affects eclipse code editor

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#20]
This is similar to the @SneakyThrows coloration issue https://github.com/peichhorn/lombok-pg/issues/7 but for @Function. It would be quite nice to somehow correct this is possible, as the code effectively becomes similar (but thankfully not identical) to when you open a text file in eclipse (colors are lost).

**Comment by peichhorn** [comment]
good news: https://github.com/jvanderhel/lombok/commit/4e831b05ec08399795d27c343b6324b5b6de3443

I will try this out right now and squeeze it into 0.10.4 if possible.

**Comment by nicholas22** [comment]
=)

**Comment by peichhorn** [comment]
Ahh to bad.. everything else looks fine but @action, @function and @Predicate still need some work.

**Comment by nicholas22** [comment]
I'm closing this. The position info looks much better now :)
