### ISSUE TITLE
@Action does not generate Action0 actions

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#22]
I think the @Action annotation does not correctly generate Action0 actions:

Action0 action = doNothing() // compilation error

@Action
public static void doNothing() {
}

This works with Functions and at the moment the workaround is to re-write the method as such:

public static Action0 doNothing()
{
&nbsp;&nbsp;&nbsp;return new Action0()
&nbsp;&nbsp;&nbsp;{

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Override
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;public void apply()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;};
}

**Comment by peichhorn** [comment]
Um Action0 should actually work.
The thing is that I didn't want to allow @Action and @Function on empty methods.
But if you need do define stuff like doNothing() then I will relax this restriction.

**Comment by nicholas22** [comment]
I don't understand why I'm getting this in Eclipse then:

  @Action
  public static void doNothing() {
  }

  @Action
  public static String doSomething(String a) {
    return a+"+something";
  }

  @Function
  public static String doSomething2(String a) {
    return a+"+something";
  }

```
Action0 action = doNothing(); // Type mismatch: cannot convert from void to Actions.Action0
Action1 action1 = doSomething(); // The method doSomething(String) in the type Main is not applicable for the arguments ()
Function1 function1 = doSomething2(); // OK
```

**Comment by peichhorn** [comment]
Damn I totally removed the return statement. This is how an action looks like now, whoops:

```
@java.lang.SuppressWarnings("all")
public static lombok.Actions.Action0 doNothing() {
  new lombok.Actions.Action0(){
    public void apply() {
      System.out.println("Action0");
    }
  };
}
```

will be fixed asap

**Comment by nicholas22** [comment]
This doesn't work still, I'm getting: @lombok.Action can be used on concrete methods only

**Comment by peichhorn** [comment]
Let me guess, the action method is empty.. I forgot to relax the restrictions on that. Initially I planned that @Action and @Method require a method body, but If you need NOP actions I must allow them.

**Comment by peichhorn** [comment]
ok now actions and functions can have empty bodies, so

```
@Action void doubleRainbow() { }
```

all the way

**Comment by nicholas22** [comment]
Haha funny ;P
I know you haven't hit a usable case yet, but imagine that for instance you have a matcher, implemented with functions, where the default action is to throw an exception due to no match. Some cases need a noop to control the flow and avoid hitting the exception. I hope it's clear enough, I will post the matcher code tonight probably.
