### ISSUE TITLE
@ExtensionMethod and anonymous class

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#24]
Anonymous classes cannot be annotated with Java annotations. This prevents extension methods from being used in  anonymous classes, because annotating the 'parent' with @ExtensionMethod does not do the trick. Is there a way around this? Thanks.

**Comment by peichhorn** [comment]
It appears that I'm traversing the source tree upward until i find the first type declaration. This is pretty bad for anonymous classes and only a pain to use for inner classes. But it should be not that hard to look at the entire type hierarchic, so I will fix this right away.

**Comment by peichhorn** [comment]
As always I've uploaded a new lombok-pg.jar (edge release)
