### ISSUE TITLE
Check @ExtensionMethod algorithmic complexity

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#27]
When using multiple classes with @ExtensionMethod, the time taken for Ecilpse auto-completion to appear is increasing in what seems to be exponential rate. Could you have a look if there is any bottleneck which causes this? 

It would follow that as you add more classes, the time taken for the auto-completion list to populate would increase linearly. But this is definitely not the case... With basically 3 classes (~200 methods) used with @ExtensionMethod, the auto-completion becomes unusable, where-as removing 1 seems to improve performance quite a bit, hence the conclusion made above...

**Comment by peichhorn** [comment]
The way it is implemented I would have expected a linear complexity as well.
Guess I have to do some profiling.

**Comment by nicholas22** [comment]
Hmm seems possible that it's a plugin then. Will re-open if this re-emerges...

**Comment by nicholas22** [comment]
I am seeing this at home as well now, so it's not the project I'm working on at work... Re-opening. To re-create is probably going to be hard, but the main things are a medium/large project and extension methods. The auto-completion takes unusually long time on certain classes. Worth investigating for presence of nested for loops or something like that...

**Comment by nicholas22** [comment]
I'm seeing it most frequently when using two extension method classes (my StringUtils, ArrayUtils) which contain like 60 methods each, maybe this helps...

**Comment by nicholas22** [comment]
Hmm restarting fixes it apparently, will see if it deteriorates soon...

**Comment by nicholas22** [comment]
I still see this but it's a 'Heisenbug'...

**Comment by nicholas22** [comment]
Haven't seen this in a while...
