### ISSUE TITLE
Yield(er) unused warning(s)

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#28]
Yield generates a field for caught exceptions that could potentially be annotated with @SupressWarning("unused") to prevent eclipse to emit a warning about its lack of use:

Warning: The value of the field $YielderOfType.cce is not used 

Code:

```
public static <TSource, TDest> Iterable<TDest> ofType(final Iterable<TSource> values, final Class<TDest> destinationClass)
{
    for(TSource item : values)
    {
      TDest temp = null;
        try
        {
            temp = destinationClass.cast(item);
        }
        catch(ClassCastException cce)
        {
        }

      yield(temp);
    }
}
```

**Comment by peichhorn** [comment]
Now exception field are annotated with @SupressWarning("unused") as you suggested.
I will upload a new edge release tomorrow.
If it still doesn't work reopen this issue.
