### ISSUE TITLE
@Predicate

### ISSUE THREAD

**Issue by peichhorn** [peichhorn/lombok-pg#29]
Now that we have `@Action` and `@Function` why not add `Predicate`.
Since this is a no-brainer, maybe cleaning up the code base of HandleFunction and HandleAction is a good way to start.

**Comment by nicholas22** [comment]
As you can see (https://github.com/nicholas22/jpropel-light/blob/master/src/propel/core/functional/predicates/Predicates.java) I'm a big fan of predicates ;)

It would be nice to have them inherit of Function1<T, Boolean> no?

**Comment by peichhorn** [comment]
Yeah it would be nice but sadly java doesn't allow primitive types as type arguments. So we have to do the same thing we did with actions. So it will be a pain in the ass to change an API from the use of Function to Predicate, since the method
signature changes. I should have introduced @Predicate together with @Function and @Action. :/

This will probably be the template for a two-argument predicate.

```
public static abstract class Predicate2<T1, T2> {
  public abstract boolean apply(T1 t1, T2 t2);

  public final Class<?> getParameterType1() {
    return TypeArguments.getClassFor(getClass(), 0);
  }

  public final Class<?> getParameterType2() {
    return TypeArguments.getClassFor(getClass(), 1);
  }
}
```

**Comment by peichhorn** [comment]
Correction (man I'm slow today ;) ): It is easily possible to inherit Function.
Same example as above, but it doesn't break existing API.

```
public static abstract class Predicate2<T1, T2> extends Function2<T1, T2, Boolean> {
  public Boolean apply(T1 t1, T2 t2)  {
    return evaluate(t1, t2);
  }

  public abstract boolean evaluate(T1 t1, T2 t2);

  public final Class<?> getParameterType1() {
    return TypeArguments.getClassFor(getClass(), 0);
  }

  public final Class<?> getParameterType2() {
    return TypeArguments.getClassFor(getClass(), 1);
  }
}
```

**Comment by peichhorn** [comment]
But I would prefer the first solution. Maybe I will provide 2 templates: Predicates and PredicateFunctions (so that APIs that use Function<..., Boolean> still works)

**Comment by nicholas22** [comment]
Why do you prefer the first?

**Comment by peichhorn** [comment]
Added support for predicate which look nothing else than:

```
public static abstract class Predicate1<T1> extends Function1<T1, Boolean> {
  public final Boolean apply(T1 t1) {
    return evaluate(t1);
  }

  public abstract boolean evaluate(T1 t1);
  }
}
```
