### ISSUE TITLE
Extension methods should suppress base methods

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#32]
Before I go and rename all my methods to avoid clashes with built-in methods in String class etc. I wonder if this is expected behaviour or a regression: 

I think I used to be able to use methods such as split, compareTo, etc. as extension methods without a problem on e.g. String classes i.e. extension methods side-by-side with methods inherited by the class and eclipse seemed to work fine. Even if it inherited a split() method and an extension method was called split() as well, eclipse would select the right one (I believe I remember saying to myself that this is too cool to be true, but I may be imagining things...).

This is not the case anymore so I think its a regression...

**Comment by peichhorn** [comment]
Yeah an extension method should supersede every other method. I wonder when I messed this one up :/

I think this is a behavior that should definitely make it's way into the documentation.

**Comment by nicholas22** [comment]
Ah phew, I was about to rename like 30000 methods or something ;P

**Comment by peichhorn** [comment]
I did some digging, actually up until now extension method never were able to supersede other methods.
So this is actually no bug, but I agree that this should be the desired behavior.
Changing the behavior for javac is pretty straight forward but doing it for eclipse might be a bit more work, so this has to wait till the weekend.

**Comment by nicholas22** [comment]
OK so I'll leave the methods as are. I'm pretty sure it used to work, but it could be something else I was impressed with ;P

**Comment by peichhorn** [comment]
I've upload a new edge release that supports this functionality.
I worked through some test scenarios to verify that @ExtensionMethod doesn't regress after adding this feature, hopefully I didn't miss anything. If times allow it, please try it yourself and report back if anything behaves differently than expected.

**Comment by nicholas22** [comment]
This is almost there, but at the moment suppresses methods of every type, even if not applicable to the type you're working with.

So if you have a Map and you use e.g. "contains" but there is an extension method "contains" applicable to String, lombok-pg uses the contains that applies to String, because it is an extension method, which is not correct. Probably there should be a check to suppress only the ones that are applicable to the type in hand and leave the other ones un-suppressed.

**Comment by peichhorn** [comment]
really? whoops... I'm on it.

**Comment by nicholas22** [comment]
Thanks ;)
Extension methods are almost completely supported which is great!

**Comment by peichhorn** [comment]
> This is almost there, but at the moment suppresses methods of every type, even if not applicable to the type you're working with.
> 
> So if you have a Map and you use e.g. "contains" but there is an extension method "contains" applicable to String, lombok-pg uses the contains that applies to String, because it is an extension method, which is not correct. Probably there should be a check to suppress only the ones that are applicable to the type in hand and leave the other ones un-suppressed.

If the issue is still present, it would be nice if you could provide a small example to reproduce it, since I'm unable to do so.
If everything is fine, please close the issue.

New Edge release, just in case some recent changes fixed it:
[lombok-pg-0.10.2-EDGE](https://github.com/downloads/peichhorn/lombok-pg/lombok-pg-0.10.2-EDGE.jar)

**Comment by nicholas22** [comment]
Will try the latest and let you know

**Comment by nicholas22** [comment]
This is working beautifully, job well done!
