### ISSUE TITLE
Deploy project artifacts to maven central

### ISSUE THREAD

**Issue by peichhorn** [peichhorn/lombok-pg#33]
The idea is make lombok-pg more accessible to all the maven folks. 

This still might need some investigation, but this should be a good place to start: http://nexus.sonatype.org/oss-repository-hosting.html

**Comment by peichhorn** [comment]
first step: issue OSSRH-2377

**Comment by peichhorn** [comment]
see https://github.com/peichhorn/lombok-pg/wiki/Grab-the-latest-version

**Comment by peichhorn** [comment]
0.10.4 release is available at: https://oss.sonatype.org/content/repositories/releases

I'm requesting sync to maven central as we speak, but it may take a while, since it is the first time.

**Comment by nicholas22** [comment]
So you wouldn't take this version down as you add newer ones right? Is this your deployment model? I'm asking because we will need to depend on this stuff so it would be nice if there were some guarantees like that. ;)

**Comment by peichhorn** [comment]
Well of cause I won't touch the released versions ;). The only thing that gets frequently updated(whenever I feel like it)  are the snapshots. But that's nothing unusual.

**Comment by peichhorn** [comment]
Not sure if you have noticed but all artifacts are now available on maven central. The search index will still need a few hours to list lombok-pg.

**Comment by nicholas22** [comment]
Great :D

**Comment by mplushnikov** [comment]
cool, thx!
