### ISSUE TITLE
@Builder for generic types

### ISSUE THREAD

**Issue by spuckydaslama** [peichhorn/lombok-pg#34]
I'd like to use `@Builder`. Would be nice to use it on generic types if even possible.

```
import lombok.Builder;

@Builder()
 public class ViewHolder<E> {
    private final List<E> list;
}
```

**Comment by peichhorn** [comment]
Weird I thought this would already work. I will look into it.

**Comment by peichhorn** [comment]
`@Builder` should work with generic types now. I will upload a new edge release jar tomorrow morning, maybe I can include another bug-fix. If you need anything else, let me know.

**Comment by spuckydaslama** [comment]
nice .. looking forward trying it out.

**Comment by hkhan** [comment]
Can you provide an example showing how to use the builder for the generic type without warnings?

Thanks

**Comment by j-walker23** [comment]
Couple years late, is it possible without warnings?

**Comment by zaretskyy** [comment]
+1

**Comment by AshwinJay** [comment]
+1
