### ISSUE TITLE
@ListenerSupport supporting generic types

### ISSUE THREAD

**Issue by spuckydaslama** [peichhorn/lombok-pg#36]
I guess this is low priority, since most of the time one does not write generic EventListener.
I happened to write some generic views lately along with the corresponding EventListener.class which also was generic.

example:

```
public interface MyEventListener<E, R> {
   public void somethingHappened(E someInfo, R someOtherStuff);
}
```

**Comment by peichhorn** [comment]
I will look into it.

**Comment by peichhorn** [comment]
Thought about it for a while and sadly I have to say: no can do.
It is simple impossible to specify or infer the types in a practical manner.
