### ISSUE TITLE
@Yield bug

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#37]
I'm getting incorrect (missing) values when using a yielder as such:

```
/**
 * Returns all values
*/
public Iterable<V> values()
{
  for (T key : map.keySet())
  {
    Map<K, V> subMap = map.get(key);
    for (K subkey : subMap.keySet())
    {
      V value = subMap.get(subkey);
      yield(value);
    }
  }
}
```

This is of a MultiMap<T, K, V> class, can provide more concrete code if necessary.  Have a look what's going on when you have some time because this works OK if I put these in a list and return them rather than yield. Maybe nested fors are a bit buggy?

**Comment by peichhorn** [comment]
I've never tested yield with nested loops and other more complex use-cases, it's very likely that the state-machine is broken in these cases. (that's why it was categorized as highly-experimental xD )
 I will look into it, once I'm done with @ExtensionMethod stuff.

**Comment by nicholas22** [comment]
OK not a priority for me, but 'nice to have'

**Comment by peichhorn** [comment]
Should work now, I will upload a new edge release tomorrow.
If it still doesn't work reopen this issue.
