### ISSUE TITLE
No autoboxing using @ExtensionMethod

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#41]
Getting a successful compilation but then a run-time verify error when doing this:

```
 if("abc.def".toCharArray().box().count('.')==1)
```

Workaround:

```
 if(Linq.count(ArrayUtils.box(value.toCharArray()), '.') == 1)
```

**Comment by nicholas22** [comment]
Another one along the same lines: 

```
 private static final Character[] ALLOWED_VARIABLE_CHARS = new char[] { 'a','b'}.box().add('-');
```

java.lang.VerifyError: (class: SomeClass, method: <clinit> signature: ()V) Expecting to find object/array on stack

Workaround:

```
 private static final Character[] ALLOWED_VARIABLE_CHARS = new char[] { 'a','b'}.box().add(new Character('-'));
```

**Comment by peichhorn** [comment]
Like you did in the second example another workaround for your first example would be:

```
if("abc.def".toCharArray().box().count(new Character('.'))==1)
```

So the issue here is, that the auto-boxing is not happening.

Note: This only happens in eclipse
