### ISSUE TITLE
Val bug

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#42]
Using dom4j library and that has some raw type usage, so I do this:

```
  for(val attribute : propElement.attributes())
  {
    val attr = (Attribute)attribute;
```

The attributes() method call returns a raw List, but I'm getting an error "propElement cannot be resolved or is not a field". Workaround: Changing the val to Object

**Comment by peichhorn** [comment]
I could reproduce this pretty easily. So I think a copy of this issue should really end up in the issue tracker of lombok.

**Comment by nicholas22** [comment]
Just wondering if you have opened an issue for this with upstream?

**Comment by peichhorn** [comment]
No, I forgot about that, thanks for the reminder.

**Comment by nicholas22** [comment]
No problem, hopefully this is going to be resolved

**Comment by peichhorn** [comment]
fixed with this commit: https://github.com/rzwitserloot/lombok/commit/3f408782de736a676ee19757894eb89c1f4ebf3b
