### ISSUE TITLE
val and @ExtensionMethod

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#45]
I've spent the last 3/4 hours trying to track what's going on with a very serious compile-time bug, I hope this can be resolved in the near future. The reason I spent so much time is that this somehow causes the javac compiler to report an error (Compile failed; see the compiler error output for details) but the 'great' thing about it, there is not freaking compiler output, it just crashes or something so I had to narrow it down by trial and error across a large code-base. Fun times. Atleast ECJ is not affected by it thankfully. Anyhow, here's how to reproduce: 

```
public static void addHandler(Function1<Object, Void> handler)
{
}

public static void main(String[] args) throws Exception
{
    val handler = Object.class.getDeclaredMethods()[0];
    addHandler(invokeMethod(new Main(), handler));
}
```

Ugly workaround which must be purged from this earth:

```
 import lombok.ExtensionMethod;
 import lombok.Functions.Function1;
 import lombok.val;
 import static propel.core.functional.projections.InvokeOneArg.invokeMethod;
 import propel.core.functional.projections.InvokeOneArg;

 public static void addHandler(Function1<Object, Void> handler)
 {
 }

 public static void main(String[] args) throws Exception
 {
   val handler = Object.class.getDeclaredMethods()[0];
   addHandler((Function1<Object, Void>)InvokeOneArg.invokeMethod(new Main(), handler));
 }
```

They both use this method:

```
@Validate
public static <T> Function1<Object, Void> invokeMethod(@NotNull final Object obj, @NotNull final Method method)
{
  return new Function1<Object, Void>() {

  @SneakyThrows
  public Void apply(Object arg)
  {
    try
    {
      method.invoke(obj, arg);
      return null;
    }
    catch(InvocationTargetException e)
    {
      // get rid of wrapper exception
      throw e.getCause();
    }
  }
};
}
```

**Comment by peichhorn** [comment]
The main issue here is that the type of `handler` cannot be determined. At least this is the error I got when I tried your example in Netbeans. (which uses javac)
So if you set the type yourself it works just fine, try: `Method handler = Object.class.getDeclaredMethods()[0];`

The fun starts to determine why `val` does not work. Let me try right quick if it works with javac7. (EDIT: issue is still present in javac7)

btw, here is another way to write `invokeMethod`:

```
@SneakyThrows
@Function
public static void invokeMethod(@NotNull final Object _obj, @NotNull final Method _method, final Object arg) {
  try {
    _method.invoke(_obj, arg);
  } catch (InvocationTargetException e) {
    throw e.getCause();
  }
}
```

**Comment by peichhorn** [comment]
Interesting

this fails:

```
import lombok.*;
import java.util.*;

@ExtensionMethod(Operations.class)
public class Main {

    public static Iterable<String> foobar() {
        return new ArrayList<String>();
    }

    public static void main(String[] args) throws Exception {
        val handler = Object.class.getDeclaredMethods()[0];
        for (String s : foobar()) {
        }
    }
}
```

while this works:

```
import lombok.*;
import java.util.*;

@ExtensionMethod(value=Operations.class, suppressBaseMethods=false)
public class Main {

    public static Iterable<String> foobar() {
        return new ArrayList<String>();
    }

    public static void main(String[] args) throws Exception {
        val handler = Object.class.getDeclaredMethods()[0];
        for (String s : foobar()) {
        }
    }
}

```

And as you see this has nothing to do with `@Function`

**Comment by peichhorn** [comment]
Should work fine now.
I've also tested the more complex example you posted above.

**Comment by nicholas22** [comment]
Thanks, so Ant should also work :)

**Comment by peichhorn** [comment]
Ant, Maven, Netbeans,.. anything that uses javac..
