### ISSUE TITLE
Exception stacktrace within @Validated method is invalid

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#46]
When a method that is annotated with @Validate throws an exception, the exception stack trace is not correct (in particular the line number). This could make debugging extremely tricky, because it points to the @Validate annotation always, instead of the actual line number. I wonder if there is some sort of magic we can pull to make line numbers work as expected...

**Comment by peichhorn** [comment]
Should be fixed now. Please try out the new [edge release](http://cloud.github.com/downloads/peichhorn/lombok-pg/lombok-pg-0.10.2-EDGE.jar).

**Comment by nicholas22** [comment]
This does not always work unfortunately

**Comment by nicholas22** [comment]
```
 public class Main
 {
    private String test;

   @Validate
   public void abc(@NotNull final String arg) {
     System.out.println(arg+" "+test.toString());
   }

   public static void main(String[] args)
       throws Exception
   {
     Main main  = new Main();
     main.abc("arg");
   }
 }
```

The stacktrace points to the @Validate annotation in this example, rather than within the 'abc()' method.

**Comment by peichhorn** [comment]
Looking at the source code I would say that it works, but I will check it  once I get home

**Comment by nicholas22** [comment]
Oops I was using 0.10.1 in eclipse
