### ISSUE TITLE
@Data extension (with @NotNull)

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#47]
A nice to have: Ability to have @Data configurable somehow so null is not accept as argument in the generated @RequiredArgsConstructor. So a way to combine @NotNull with @Data is what I'm basically asking, as this is a fairly common use-case, which at the moment necessitates the explicit creation of a constructor, despite using @Data...

**Comment by peichhorn** [comment]
You can already do this with:

```
@Data
class SimpleBean {

  @lombok.NonNull
  private final String value;
}
```

But I see, that the coexistence of @lombok.NonNull and @lombok.Validate.NotNull is confusing and less than optimal.

**Comment by nicholas22** [comment]
Would renaming it to lombok.Data.NotNull make things a bit clearer?

**Comment by peichhorn** [comment]
I can't do that since `@lombok.NonNull` is a feature of lombok itself. So I'm really not sure if there is anything I can do.

**Comment by peichhorn** [comment]
I'm going to merge this issue into issue #80.
