### ISSUE TITLE
@Runnable

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#48]
Something along the lines of functional programming, @Runnable would be a nice addition to avoid anonymous inner classes being sprinkled all over the place for small tasks that do not require a dedicated class. Example:

```
 @Runnable
 public void performMyCoolTask() {
 // do stuff here
 }
```

Then it would be nice to be able to do:

```
 Executors.newSingleThreadExecutor().execute(performMyCoolTask());
```

This would probably be quite easy given your knowledge of @Function ;)

**Comment by peichhorn** [comment]
This does the trick:

```
@Action(template = Runnable.class)
public void performMyCoolTask() {
 // do stuff here
 }
```

I could rename the annotation method to `value`, since I'm pretty sure no one uses this yet (pretty advanced feature and badly documented). So you would end up with `@Action(Runnable.class)`.
I know, not as elegant as you want it to be. ;)

**Comment by nicholas22** [comment]
It works! I dont' understand how template works yet but learning... xD

**Comment by nicholas22** [comment]
Just noticed that the @Action has the Eclipse auto-importation bug present, perhaps should I open a separate issue

**Comment by peichhorn** [comment]
No need, I have already fixed it in my local repo, since I stumbled over it as I was trying out the example I've posted.
I will probably push the changes tomorrow morning.

**Comment by nicholas22** [comment]
Sweet

**Comment by peichhorn** [comment]
The files are up I've also fixed "Refactor > Rename" for method arguments that were annotated with lombok.Validate.NotNull, lombok.Sanitize.With and so on...
