### ISSUE TITLE
Upgrade to lombok 0.10.4

### ISSUE THREAD

**Issue by MiguelGL** [peichhorn/lombok-pg#49]
Project lombok recently upgraded to a 0.10.2 release, fixing some (and few IIRC) issues on it way. It would be nice to have lombok-pg synchronised to that new release. 

Thanks for such a great library BTW!!

**Comment by peichhorn** [comment]
Sure thing.

**Comment by peichhorn** [comment]
I had to upgrade lombok 0.10.3 (which as of 0.10.2 marks the edge releases between 0.10.2 and 0.10.4), see commit 
[0d75d56fcef943d1a35f1169386830066371c12d](https://github.com/rzwitserloot/lombok/commit/0d75d56fcef943d1a35f1169386830066371c12d)

**Comment by peichhorn** [comment]
Let's upgraded to lombok 0.10.4 before releasing on Friday.
