### ISSUE TITLE
@ExtensionMethod with missing symbol

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#51]
The newest release introduces an NPE bug when using @ExtensionMethod and an unresolved/missing method, when said method is part of the class whose methods are used as extension methods:

Description Resource    Path    Location    Type
Internal compiler error: java.lang.NullPointerException at lombok.eclipse.agent.PatchExtensionMethod.resolveType(PatchExtensionMethod.java:157) CustomOutputAdapter.java    /DataServices/src/dataservices/persistence/entities/outputAdapters  line 0  Java Problem

So in more detail the problem is as follows:

```
 ReflectionUtils.getMethods(OutputAdapter.class, true).where(contains(SAVE_DATA_METHOD)).single();
```

In the above snippet, the contains() method is missing (not imported statically yet) and the class which contains the above uses @ExtensionMethod on my StringUtils class (which has a contains() method), so this somehow triggers the NPE.

This is easily rectified by statically importing the dependency (import static propel.core.functional.predicates.Objects.contains), but I just copy/pasted the snippet above in a new file and it created 600 entries in the Eclipse problems pane, so it probably messes with ECJ in some way, hence I'm reporting it. Not a major problem.

**Comment by peichhorn** [comment]
Sounds like a annoying bug.. I will look into it when I fix the other issues with @ExtensionMethod.
