### ISSUE TITLE
maven repository upload

### ISSUE THREAD

**Issue by mplushnikov** [peichhorn/lombok-pg#52]
Please upload the lombok-pg artifacts to a central maven repository!

**Comment by peichhorn** [comment]
Ah yes, I plan on doing so, see issue #33.
But depending on how urgent this is, I can prioritize it higher.
Am I assuming correct, that you are the author of the lombok-intellij-plugin?
Knowing the documentation of lombok-pg is at the time pretty horrific,
just let me know if I can help you out with anything.

**Comment by mplushnikov** [comment]
Oh, sorry I didn't see the issue #33. I close this as duplicate.
Yes, I'm author of intellij-plugin for lombok and got a question about support for lombok-pg. (http://code.google.com/p/lombok-intellij-plugin/issues/detail?id=12)
I like to work with maven and it would be really helpful to have lombok-pg in maven-central like lombok self.
