### ISSUE TITLE
@Builder should consider @NonNull annotations

### ISSUE THREAD

**Issue by ggtools** [peichhorn/lombok-pg#54]
Currently @Builder check the attributes for the final keyword in order to find out the mandatory and the optional attributes. In some context (hibernate/JPA entities for instance), using final attributes is not an option (short version: hibernate builds the entities from a default constructor and then sets them using reflexion).

It'll be nice to have lombok-pk checking both the final keyword and the @lombok.NonNull annotation on the field to find out the mandatory fields.

**Comment by peichhorn** [comment]
Sounds reasonable.

**Comment by peichhorn** [comment]
The release (0.10.2) containing this fix will probably be eleased this Friday.

**Comment by ggtools** [comment]
That's great, thanks.
