### ISSUE TITLE
@Cleanup without value is broken for non-Closeable classes

### ISSUE THREAD

**Issue by abryzak** [peichhorn/lombok-pg#55]
After upgrading to the latest lombok-pg, `@Cleanup` is broken for classes that have a `close` method but don't implement `Closeable`. The following test demonstrates that `close` isn't called.

``` java
import lombok.Cleanup;

public class CleanupTest {

    public void close() {
        System.out.println("close called");
    }

    public static void main(String[] args) throws Exception {
        @Cleanup
        CleanupTest closeable = new CleanupTest();
    }

}
```

As a workaround, you can pass a `"close"` value to the annotation.

**Comment by abryzak** [comment]
It also will complain about `IOException` not being caught.

**Comment by peichhorn** [comment]
I'm afraid that is no bug, but rather a somewhat expected side-effect of issue #50.
If you want `@Cleanup` to just call a method, you need to specify a method name now. So in your case:

``` java
@Cleanup("close")
CleanupTest closeable = new CleanupTest();
```

Please not that this is valid in both lombok and lombok-pg.

If no method name is provided the assumption in lombok-pg is, that you want a cleanup block
for `Closeable`s. In this case the uncaught `IOException` is also intended.

If this change sounds unreasonable to you, please let me know.

EDIT: Either way I will make sure that the documentation reflects changes between lombok and lombok-pg.

**Comment by abryzak** [comment]
If it's intended behaviour that's fine, just wanted to make sure as it caught me off guard.

**Comment by peichhorn** [comment]
Yeah sorry for that.
