### ISSUE TITLE
Transient for propertySupport

### ISSUE THREAD

**Issue by psysiu** [peichhorn/lombok-pg#62]
When using @BoundPropertySupport it generates 
`private final java.beans.PropertyChangeSupport propertySupport = new java.beans.PropertyChangeSupport(this);`
It would be nice (maybe optional) to generate using transient to avoid beans serialisation issues:
`transient private final java.beans.PropertyChangeSupport propertySupport = new java.beans.PropertyChangeSupport(this);`

This leads to propertySupport = null problem after deserialization, it could be avoided by adding readResolve method which is called after deserialization but before the object is returned.
<code>ANY-ACCESS-MODIFIER Object readResolve() throws ObjectStreamException {
        this.propertyChange = new java.beans.PropertyChangeSupport(this);
}</code>

**Comment by peichhorn** [comment]
The PropertyChangeSupport field is now transient and gets initialized lazily. I didn't like the idea of using the readResolve method to initialize the field.
I've uploaded a new SNAPSHOT release, so you can try it out.
