### ISSUE TITLE
Upgrade to lombok 0.10.6

### ISSUE THREAD

**Issue by MiguelGL** [peichhorn/lombok-pg#65]
Project lombok recently released a 0.10.6 release, fixing some bugs and one memory leak problem when using it within NetBeans leading it eat up memory as if there was no such day as tomorrow. 

Frequent IDE restarts are required to deal with the issue, and that makes NB+lombok-pg users (like me :) sad. It would be great to have a synchronized 0.10.6 lombok-pg release!

Thanks so much again for this great lib, really.

**Comment by peichhorn** [comment]
As you suggested I'm skipping 0.10.6 in favor of 0.10.8
