### ISSUE TITLE
@ExtensionMethod with overloaded methods

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#66]
When there are two or more applicable methods, I think the logic at the moment just selects the first one. It would be nice to select the most appropriate one by examining the argument class types and checking if the two are assignable...

**Comment by nicholas22** [comment]
For instance, I have two methods as such:

```
public static <T> List<T> toList(T[] array) { ... }
public static <T> List<T> toList(Collection<T> col) { ... }
```

When using @ExtensionMethod, on an array:

```
Integer[] ints = new Integer[] { 1,2,3 };
ints.toList(); // error
```

I get an error that toList() is not applicable to array and from the error message I see Eclipse is trying to apply the Collection<T> overload... Not sure if this example works as such, it depends as it chooses the first one in an alphabetically sorted list. The correct behaviour would be to perform some type checking and attempt to use the right overloaded method.

**Comment by peichhorn** [comment]
The main issue here is, that the method with the Collection was considered an applicable extension method for the Integer array.

Just verified it again, this issue was fixed a while ago.

**Comment by peichhorn** [comment]
This is commit that fixed it: https://github.com/peichhorn/lombok-pg/commit/abca43ac9dcfb49eed123f3fb31f8b32c38a3226
