### ISSUE TITLE
Consider skipping 0.10.6 milestone in favour of 0.10.8

### ISSUE THREAD

**Issue by MiguelGL** [peichhorn/lombok-pg#67]
Project Lombok recently released the 0.10.8 version, shipping many bugfixes and stabilising some stuff from 0.10.2 up to this release. Please read about it on https://groups.google.com/forum/#!topic/project-lombok/zHiVOz1aFFg

It may be a good idea to skip lombok-pg's 0.10.6 and just move the pointer forward to synch with this new lombok 0.10.8. That's my suggestion. 

Thanks again!

**Comment by nicholas22** [comment]
bump!

**Comment by peichhorn** [comment]
Sorry for my absence, I'm on it.

**Comment by peichhorn** [comment]
I have been testing lombok-pg with lombok 0.10.8 for a few days now.. and I couldn't find any regressions.. 

You can find a new snapshot release here:
https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/0.10.8-SNAPSHOT/

Once I've fixed some other major issues I will push out 0.10.8.

**Comment by MiguelGL** [comment]
This is great news, I'll try the SNAPSHOT release and report back should I find any issues. 

Thanks again, and congrats for the work, both lombok and lombok-pg are some real craftwork! (I even more realised that when trying to -of course unsucessfully :(- lern it and migrate myself).

**Comment by nicholas22** [comment]
Could not find the release on Maven, could we please close once available? :)

**Comment by nicholas22** [comment]
Still no release... Isn't this supposed to happen automatically once in snapshot? I'm checking at mvnrepository.com (not sure if that's correct...)

**Comment by peichhorn** [comment]
Sorry that I didn't read this earlier.
Snapshots are only available in the oss snapshot repository:

https://oss.sonatype.org/content/repositories/snapshots/

If you want to access the files directly, you can find them here:

https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/0.10.8-SNAPSHOT/

I try to squeeze in some bugfixes this weekend so I can roll out 0.10.8.

**Comment by nicholas22** [comment]
Ah.. right, thanks for the clarification! The impression I had was that once in snapshot they sync automatically...
