### ISSUE TITLE
ast.ClassDecl and superclass generation

### ISSUE THREAD

**Issue by lqd** [peichhorn/lombok-pg#69]
Hey Philipp,

Am I missing something or ClassDecl doesn't have a method to set the superclass (even though the field exists) ? It does have the ones for super interfaces though.

So I added this to the class:

```
public ClassDecl extending(final TypeRef type) {
    superclass = type;
    return this;
}
```

and voilà :)

**Comment by lqd** [comment]
Oh btw, your ast makes writing Lombok handlers SOOOO much easier and more fun. Great job :)
The official lombok.ast looks interesting too.

**Comment by peichhorn** [comment]
Hi there, thanks for letting me know.

> The official lombok.ast looks interesting too.

In the long run I would like to use lombok.ast but before that it needs to be tightly integrated into lombok.
