### ISSUE TITLE
SneakyThrows affects the Eclipse code editor

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#7]
I don't know if you have noticed before, but the SUPER-useful annotation @SneakyThrows, affects the coloration of the Eclipse code editor in the code immediately after it. Somehow, eclipse believes that portions of the file are what seems to be text (instead of code). I have uploaded a screenshot... here: http://i54.tinypic.com/2ivbkzk.png

The right colors can be seen near the end of the code in the screenshot.

**Comment by peichhorn** [comment]
Yeah this is a known issue of lombok. It has something to do with the position-information you give the "hidden" AST-Elements.

**Comment by nicholas22** [comment]
Would be nice to have a look if it can be fixed at some point, because it
prevents type lookups (e.g. following a type's
implementation/super/interface/etc. when you shift+click) as well, which is
not great when you're doing reviews...

**Comment by nicholas22** [comment]
Actually type lookups work OK... It's just the highlighting...

**Comment by nicholas22** [comment]
Partial workaround: manually moving the @SneakyThrow-ing method higher up the code, e.g. from line 100, to line 10. This helps because everything above it gets the 'color-blindness' effect, but everything below maintains the right coloration... (Eclipse)

**Comment by nicholas22** [comment]
Some people have complained about this to me. Not a major nuisance though. Any positional info magic to improve this?

**Comment by peichhorn** [comment]
It is definitely an issue with the position info and annoys myself enough to get a high priority. So I will look into it soon. No promises though. xD

**Comment by peichhorn** [comment]
good news: https://github.com/jvanderhel/lombok/commit/4e831b05ec08399795d27c343b6324b5b6de3443

I will try this out right now and squeeze it into 0.10.4 if possible.

**Comment by peichhorn** [comment]
Guess what, it's fixed now.. xD (best news for me, yield looks fine)
