### ISSUE TITLE
ScalaIDE breaks @AutoGenMethodStub 

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#70]
I think @AutoGenMethodStub is not working as expected. I'm using 0.10.4 (release)

**Comment by peichhorn** [comment]
Not sure if it is still relevant, but please elaborate on your comment. I need details, as it works for me. ;)

**Comment by peichhorn** [comment]
Please reopen this issue if need be.

**Comment by nicholas22** [comment]
I'm using 0.11.0 and seeing an error message when using the following code within Eclipse:

```
@AutoGenMethodStub
public class Blah
    implements MouseListener
{

}
```

Error messages: The type Blah must implement the inherited abstract method MouseListener.mouseClicked(MouseEvent) 

(...and all the other public methods of the interface)

**Comment by nicholas22** [comment]
The workaround I'm using is a @Delegate to an implementor class

**Comment by peichhorn** [comment]
Sorry I can't reproduce the issue with the code you've posted.

**Comment by nicholas22** [comment]
I'll send you an eclipse project to see if you can repro...
Using lombok-pg v0.11.0 and Java 1.6

**Comment by peichhorn** [comment]
I took a look at the project you send me and everything worked fine.
I even installed the provided lombok-pg version located in the lib folder.

What eclipse version are you using? I've tried it with 3.6.0, 3.7.0 and 3.7.2.
Are you absolutely certain that you installed lombok-pg to the correct eclipse installation,
since the phenomenon you described sounds like lombok is not present at all.

I take any information you got to narrow down the issue. ;)

**Comment by nicholas22** [comment]
How strange... This is what I'm using:

Eclipse IDE for Java Developers
Version: Indigo Release
Build id: 20110615-0604
Lombok v0.11.0 "Burning Emu" is installed. http://projectlombok.org/

I can use everything else such as extension methods, etc...

**Comment by nicholas22** [comment]
I downloaded and installed a fresh Eclipse copy and yea, it works.
No idea what's causing it, as everything else works. Could it be some other processor?
I have the Scala IDE 2.0 (with built-in scala 2.9.3-RC2) installed and in the past I had seen some interleaving with other processors, which I reported and they fixed. Do you have Scala installed?

**Comment by peichhorn** [comment]
Oh sorry, totally forgot to answer that.. no I don't have Scala IDE installed.. I'm using IntelliJ IDEA for my scala stuff...

**Comment by nicholas22** [comment]
OK- will wait for 2.9.3 GA and upgrade, to see if it persists. It's some Eclipse-related issue but a weird one huh?...

**Comment by peichhorn** [comment]
Yeah it sure is.

**Comment by peichhorn** [comment]
Just out of curiosity I've installed the latest nightly build of the ScalaIDE 2.9.x branch and I can reproduce this issue.
So it is definitely a bug. Somehow ScalaIDE interferes with the way @AutoGenerateMethodStub works.

**Comment by peichhorn** [comment]
The issue is, that ScalaIDE creates a pointcut with AspectJ for methods lombok-pg manipulates.

`scala.tools.eclipse.contribution.weaving.jdt.jcompiler.MethodVerifierAspect`

**Comment by nicholas22** [comment]
Should I create a bug report for this with them, or would you rather do so (being more knowledgeable of the internals?)

**Comment by peichhorn** [comment]
Fixed it inside lombok-pg.. gonna release a new snapshot now..

**Comment by peichhorn** [comment]
New snapshot is available at: [link](https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/0.11.3-SNAPSHOT/)

If it should fail again in the future, please let me know. Because if it does, it means I have to go through the guts of ScalaIDE again. xD

**Comment by nicholas22** [comment]
Wow nice one dude, thanks! ;)
