### ISSUE TITLE
Any timeline for upgrade to lombok 0.11.0

### ISSUE THREAD

**Issue by rvakkada** [peichhorn/lombok-pg#75]
lombok-0.11.0 has simpflied the internals. Any timeline to move towards it

**Comment by peichhorn** [comment]
I've already upgraded to lombok 0.11.0 on a local branch but since 2 tests are still failing, I would like to investigate them first.

**Comment by peichhorn** [comment]
I've just committed the changes, still need to update the buildfiles though.

**Comment by rvakkada** [comment]
Can u provide a quick notes as to how to build lombok-pg

----- Original Message -----

**Comment by peichhorn** [comment]
If you haven't applied any changes to lombok it is a lot simpler once I've updated the buildfiles.

You build it exactly how you build lombok, by executing the ant target 'dist'.
If you have modified the lombok source, for instance via applying the patches
located in 'lombok-pg/src/patches', you need to make sure that the modified
lombok artifact ends up in the 'lombok-pg\lib\build' and 'lombok-pg\lib\test'
directory. You can do this by simply copying it there or by installing the
artifact to a local ivy repository and adjusting the buildfiles.

**Comment by peichhorn** [comment]
The progress of updating the buildfiles will be tracked in this issue: #79.
