### ISSUE TITLE
Add clear() Method to @Builder

### ISSUE THREAD

**Issue by rvakkada** [peichhorn/lombok-pg#76]
Is it possible to provide  a clear method in builder such that if we want to reuse the same builder instance such that we can reuse it

**Comment by peichhorn** [comment]
Well it would be easily possible to add a `clear()` method to the Builder, that would reset its field to the default values, but I don't see what big benefit this method would bring. I'm not sure which machines you are targeting but instantiating a new Builder is not that expensive.
It would be nice if you could explain your need for this method a bit more.

**Comment by rvakkada** [comment]
we are using mostly LMAX kind of architecture with DDD appoach where we do not want to create unncecessary objects and our code is going to be single threaded. SO we want to reuse the same instance of builder.

**Comment by peichhorn** [comment]
Ah ok, I will see what I can do.

**Comment by peichhorn** [comment]
> @rvakkada:
> Please expose a getBuilder method which clears all the fields (reset method) and return the inface to build the first required field or optionalDef Builder if all the fields are optional

**Comment by peichhorn** [comment]
Done..
Usage example:

``` java
import lombok.Builder;

@Builder(allowReset=true)
public class Person {
    private String name;
    private String firstname;
    private int age;
}

private Iterable<Person> reuseInstance() {
  Person.OptinalDef builder = Person.person();
  yield(builder.firstname("Chuck").name("Norris").age(72).build());
  builder.reset();
  yield(builder.firstname("Foo").name("van Bar").age(42).build());
  builder.reset();
  }
}
```

**Comment by rvakkada** [comment]
How will the inheritance part work ( I know it is a different issue)

----- Original Message -----

**Comment by peichhorn** [comment]
I'm not yet sure how exactly it will work. I have a view ideas, but I need to evaluate them first.

**Comment by rvakkada** [comment]
Thanks
Let me know how it goes

----- Original Message -----

**Comment by rvakkada** [comment]
Is it possible to get this done in the next release. Also how do I access the reset method (which version of lombok-pg  will have it)

Thanks for the quick turn around
-----Original Message-----

**Comment by peichhorn** [comment]
> Is it possible to get this done in the next release.

Do you mean `@Builder` working with inheritance? If so, please use the other issue and probably yes. ;)

> Also how do I access the reset method (which version of lombok-pg  will have it)

The next version which is 0.11.4. But I can deploy a snapshot release if you like.

**Comment by rvakkada** [comment]
The reset method is available only on OptionalDef. Can you make it available as the first final field builder interface

-----Original Message-----

**Comment by peichhorn** [comment]
Oh sorry, I've missed that.

**Comment by peichhorn** [comment]
Done.

0.11.4-SNAPSHOT can be found here: [link](https://oss.sonatype.org/content/repositories/snapshots/)

**EDIT** Sorry the snapshot is not available yet, since I get Bad Request errors when deploying the artifact.. I need to investigate this once I get home from work.
**EDIT 2** Now the snapshot is available..

**Comment by peichhorn** [comment]
The snapshot I've uploaded did not contain a proper fix for this issue, please use the snapshot I've uploaded just now.
Sorry for the inconvenience.

**Comment by rvakkada** [comment]
Any idea when the builder can work with super class variables

-----Original Message-----

**Comment by peichhorn** [comment]
> Any idea when the builder can work with super class variables

I plan on including a solution for Issue #78 in the 0.11.4 release, but I have not yet ironed out any details.
It's not an easy topic. I'm going finish up the idea this week. So maybe the feature is available next week,
but I can't guarantee you that.

**Comment by rvakkada** [comment]
Thanks.
