### ISSUE TITLE
Missing dependencies when compiling

### ISSUE THREAD

**Issue by ggtools** [peichhorn/lombok-pg#79]
When I retrieve a fresh copy of lombok-pg and I tried to create the eclipse project files ant ends up with the following error:

```
[ivy:resolve]     http://repo1.maven.org/maven2/de/java2html/java2html/5.0/java2html-5.0.pom
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]       :: org.eclipse.core#org.eclipse.core.runtime;3.6.0.v20100505: not found
[ivy:resolve]       :: de.java2html#java2html;5.0: not found
[ivy:resolve]       ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve] 
[ivy:resolve] :: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
```

**Comment by peichhorn** [comment]
I'm still working on some changes in lombok, for instance `@Data(callSuper=true)`.
Right after that, I will have a look at the buildfiles, since the customized lombok 0.11.0 version is missing, there as well right now. So I have it on the radar. But thanks for the heads-up.

**Comment by peichhorn** [comment]
I've just updated and tested the buildfiles. Everything works fine now.

**Comment by ggtools** [comment]
Strange, I still have the same issue on those two files. Apparently there is an issue with repo1 which returns the pom from both artifacts gzipped. Switching to repo2 fixed the problem for me.

**Comment by peichhorn** [comment]
Thanks.
