### ISSUE TITLE
NPE checking annotation

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#8]
How many times do we have to check for NPE, just so that we catch the null reference early on? Wouldn't it be nice to have an annotation that is applicable to method such as:

@NullCheck
void test(String first, String second) {
}

It could throw a new NullPointerException("first") or new NullPointerException("second"), provided the argument named can be captured...

**Comment by peichhorn** [comment]
Already done it:

```
/**
 * Explicitly turns on validation for all method
 * parameter annotated with {@code @Validate.With("methodname")},
 * {@code @Validate.NotNull()} and {@code @Validate.NotEmpty()}.
 * <p>
 * <b>Note:</b> All lombok-pg method-level annotations automatically
 * trigger a parameter validation.
 */
@Target(METHOD) @Retention(SOURCE)
public @interface Validate {
    /**
     * Method that should be used to validate the parameter.
     * <p>
     * <b>Note:</b> This works with all types, but the parameter type
     * has to match the method signature.
     */
    @Target(PARAMETER) @Retention(SOURCE)
    public static @interface With {
        String value();
    }

    @Target(PARAMETER) @Retention(SOURCE)
    public static @interface NotNull {
    }

    @Target(PARAMETER) @Retention(SOURCE)
    public static @interface NotEmpty {
    }
}
```

I'm going to cook up some examples real quick. And again the documentation of lombok-pg is as bad as it gets. xD

**Comment by nicholas22** [comment]
Hah, nice stuff once again.
I'll try to contribute some but may need some help (a one-liner) on each of the undocumented ones, so I can go and create some more complex examples, because it's hard to document that which you are not aware of ;)

**Comment by peichhorn** [comment]
Just found a bug in the @Validate.With mechanism.. I will fix it real quick and post an example afterwards.

**Comment by peichhorn** [comment]
```

import lombok.Validate;
import lombok.Validate.*;

public class TestValidation {

    @Validate
    public void explicitValidation(@NotEmpty String wontBeEmpty, @With("emailCheck") String hasToBeAnEmail, @NotNull Class<?>... wontBeNull) {
        System.out.println("wontBeEmpty: " + wontBeEmpty);
        System.out.println("hasToBeAnEmail: " + hasToBeAnEmail);
        System.out.println("wontBeNull: " + wontBeNull);
    }

    boolean emailCheck(final String emailSuspect) {
        // apply an awesome regex
        return true;
    }
}


```

Uploading as we speak...

**Comment by peichhorn** [comment]
Here an example that all method-level annoations support @Sanitize and @Validate.

```

import java.util.*;

class LockPlain {
    private Map<String, String> dictionary = new HashMap<String, String>();

    @lombok.WriteLock("dictionaryLock")
    public void put(final @lombok.Validate.NotEmpty @lombok.Sanitize.With("checkKey") String key, final String value) {
        dictionary.put(key, value);
    }

    @lombok.ReadLock("dictionaryLock")
    public String get(final @lombok.Validate.NotEmpty @lombok.Sanitize.With("checkKey") String key) {
        return dictionary.get(key);
    }

    private String checkKey(final String key) {
        // do something;
        return key;
    }
}

```

**Comment by nicholas22** [comment]
That's cool, but with strings being untyped it's easy to make mistakes e.g.
when refactoring. It would be nice to show warnings when the method is not
found.

**Comment by peichhorn** [comment]
If you rename the method you should get a compile Error at the first line of the file, saying: `The method emailCheck(String) is undefined for the type 
TestValidation`. But your right I could improve this.

**Comment by nicholas22** [comment]
Tried the @Validate on a constructor and it says it is not valid for that location. Is this a feature or a bug? :)

**Comment by peichhorn** [comment]
It's a bug. Apparently I forgot to add ElementType.CONSTRUCTOR to @Validate and @Sanitize. whoops

Fixed it real quick. Thx for spotting that.

**Comment by nicholas22** [comment]
Thanks!
