### ISSUE TITLE
Dependency issue 0.10.8 -> 0.11.0

### ISSUE THREAD

**Issue by tinne** [peichhorn/lombok-pg#81]
The code heavily relies on the 0.11.0 experimental features of @Accessor, still, the build process tries to build against 0.10.8 - and fails.

It must be something more complicated than changing versions in buildScripts/ivy.xml, still I dont' understand: fixing just the version makes the script try to download from repo1.../projectlombok/org/lombok/..., fixing the order of org and projectlombok wrecks dependency management completely:

[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           ::          UNRESOLVED DEPENDENCIES         ::
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::
[ivy:resolve]           :: org.projectlombok#lombok;0.11.0: configuration not found in org.projectlombok#lombok;0.11.0: 'build'. It was required from com.github.peichhorn#lombok-pg;SNAPSHOT build
[ivy:resolve]           ::::::::::::::::::::::::::::::::::::::::::::::

Looks like I also need to manipulate buildScripts/ivyRepo/*, but how?

**Comment by peichhorn** [comment]
Thanks for reporting. I'm actually just working on it, since I plan to release lombok-pg 0.11.0 today.

**Comment by peichhorn** [comment]
Merged into Issue #79

**Comment by peichhorn** [comment]
I've just updated and tested the buildfiles. Everything works fine now.
