### ISSUE TITLE
@ToString/@Data performance

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#86]
Perhaps something to take up with up-stream, or develop within lombok-pg and then issue a pull-request. 
The @ToString annotation (and @Data) concatenate object properties when toString() is called. It would probably be preferable to use a StringBuilder and avoid the performance and garbage hit.

**Comment by ggtools** [comment]
The compiler is automatically converting string concatenations to StringBuilder operations. If you use jad to decompile a lombokized class you'll see that the toString is actually:

```
return (new StringBuilder("ClassName(attr1=")).append(getAttr1()).append(",attr2=").append(getAttr2()).append(")").toString();
```

**Comment by peichhorn** [comment]
I don't see the issue myself, since the generated toString() method is just one huge (string concatenation) statement and therefore only one StringBuilder instance will be created. Naturally, if there were multiple lines (multiple statements) or even a loop, it would be a totally different story.

**Comment by nicholas22** [comment]
Perhaps you are using javac, I'm not seeing StringBuilders used when de-compiling the lombokized class... Is this improved in a later version perhaps? I'm on 0.10.4...

**Comment by peichhorn** [comment]
No this hasn't changed in a while. Are you using [JD](http://java.decompiler.free.fr/) ?

**Comment by nicholas22** [comment]
Yup, is there a known issue with it or something? And I actually only decompiled @Data, not @ToString. Will try the latest version and re-open if needed...

**Comment by nicholas22** [comment]
Easily re-producible with 0.11.0 and Eclipse...

**Comment by peichhorn** [comment]
I'm pretty sure that [JD](http://java.decompiler.free.fr/) does some magic to recreate the string concatenation, but I'm going to look at it again. Old Decompiler like JAD display StringBuilder operations.

**Comment by ggtools** [comment]
Just made the test. I start with the following class:

``` java
@ToString
public class ToStringTest {
    private String a;

    private int b;

    private long c;

    private String[] d;
}
```

Decompiling with jad give this version to `toString`:

``` java
public String toString()
{
    return (new StringBuilder("ToStringTest(a=")).append(a).append(", b=").append(b).append(", c=").append(c).append(", d=").append(Arrays.deepToString(d)).append(")").toString();
}
```

While jd gives:

``` java
public String toString()
{
    return "ToStringTest(a=" + this.a + ", b=" + this.b + ", c=" + this.c + ", d=" + Arrays.deepToString(this.d) + ")";
}
```

For the brave, the bytecode:

```
public toString()Ljava/lang/String;
   L0
    LINENUMBER 5 L0
    NEW java/lang/StringBuilder
    DUP
    LDC "ToStringTest(a="
    INVOKESPECIAL java/lang/StringBuilder.<init>(Ljava/lang/String;)V
    ALOAD 0
    GETFIELD ToStringTest.a : Ljava/lang/String;
    INVOKEVIRTUAL java/lang/StringBuilder.append(Ljava/lang/String;)Ljava/lang/StringBuilder;
```

We clearly see that the compiler replaced the string concatenation with operations on a `StringBuilder` and that JD is doing a hell of a good job to reconstruct the initial concatenation ops from the `StringBuilder` ops.

**Comment by nicholas22** [comment]
Nice detective work :) Thanks for clarifying. Did you compile this using Eclipse?

**Comment by ggtools** [comment]
Yes I did compile it with Eclipse.

**Comment by nicholas22** [comment]
Cool thanks =) 
Seems that Philipp was right all along.
