### ISSUE TITLE
val and yield()

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#88]
I'm getting an error when using val and assigning an iterable. The error message is difficult to trace because the line number is always "1", which is not the right one. Maybe an AST issue?

``` java
    @Validate
    public static <TSource, TResult> Iterable<TResult> selectMany(@NotNull final Iterable<TSource> values, @NotNull final Function1<TSource, List<TResult>> selector)
    {
      for (TSource item : values)
      {
        val subItems = selector.apply(item); // works if declared as List<TResult>
        if (subItems != null)
        {
          for (TResult subItem : subItems)
            yield(subItem);
        }
      }
    }
```

Error message:
The method iterator() is undefined for the type val, line 1 Java Problem

**Comment by peichhorn** [comment]
Thanks for the detailed report, I'm pretty sure issue is that `yield(..)` get's handled before `val`. Shouldn't be to hard to fix.

**Comment by peichhorn** [comment]
The javac part is done. Sadly the eclipse part will be a lot harder to fix, but I'm on it.

**Comment by nicholas22** [comment]
Thanks!

**Comment by peichhorn** [comment]
done
