### ISSUE TITLE
@ImplicitConstructor

### ISSUE THREAD

**Issue by nicholas22** [peichhorn/lombok-pg#90]
Many times when designing for injection and immutability, there is a need to use final fields and pass arguments from sub-class to super-class constructors. More often than not, these are just pass-through arguments creating boilerplate in repeating constructors. It would be nice to have an @ImplicitConstructor which works like a @RequiredArgsConstructor but relays arguments to the super constructor.

**Comment by peichhorn** [comment]
Please try: @NoArgsConstructor (callSuper=true)
I introduced this feature in 0.11.0..

**Comment by nicholas22** [comment]
Tried but no luck, I'm using 0.11.0

**Comment by peichhorn** [comment]
Quick Test: Compiled with eclipse and decompiled with JD
( Eclipse Juno 4.2 + lombok-pg 0.11.0)

**Before**

``` java
package demo;

@lombok.RequiredArgsConstructor
public class AbstractPojo {
    private final String name;
    private final Integer value;
}
```

``` java
package demo;

@lombok.NoArgsConstructor(callSuper=true)
public class Pojo extends AbstractPojo {

}
```

**After**

``` java
package demo;

public class AbstractPojo {
    private final String name;
    private final Integer value;

    @java.beans.ConstructorProperties({"name", "value"})
    public AbstractPojo(String name, Integer value) {
        this.name = name;
        this.value = value;
    }
}
```

``` java
package demo;

public class Pojo extends AbstractPojo {

    @java.beans.ConstructorProperties({"arg0", "arg1"})
    public Pojo(String arg0, Integer arg1) {
        super(arg0, arg1);
    }
}
```

**Comment by nicholas22** [comment]
Ah very nice! I think I used @RequiredArgsConstructor, I should have read the post more carefully >:)

**Comment by peichhorn** [comment]
@RequiredArgsConstructor would work as well if configure it with `callSuper=true`

**Comment by tejashpshah** [comment]
I am using latest version 1.16 and I can't find option to use callSuper=true in it. 
I also checked the sources https://github.com/rzwitserloot/lombok/blob/master/src/core/lombok/AllArgsConstructor.java it also do not have  callSuper=true
Is this feature removed?
