### ISSUE TITLE
Handle @ExtensionMethod with future lombok 0.11.2

### ISSUE THREAD

**Issue by peichhorn** [peichhorn/lombok-pg#91]
@ExtensionMethod got moved up to lombok, which is awesome.
But for existing users of lombok-pg the different packages of @ExtensionMethod are a minor issue..

lombok: `lombok.experimental.ExtensionMethod`
lombok-pg: `lombok.ExtensionMethod`

One solution would be to handle both `lombok.experimental.ExtensionMethod` and `lombok.ExtensionMethod` and therefore patch lombok again. -.-

**Comment by nicholas22** [comment]
Sounds like a good plan to me (albeit more work for you unfortunately). I suppose after a while it will be non-experimental and would merge into 1?

**Comment by peichhorn** [comment]
> I suppose after a while it will be non-experimental and would merge into 1?

Yeah I think so.

**Comment by peichhorn** [comment]
done...
