### ISSUE TITLE
quiet: @Cleanup

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#92]
This is a dupe of an RFE I have filed with canonical Lombok

http://code.google.com/p/projectlombok/issues/detail?id=388

It would be great if there were a "quiet" option to @Cleanup which essentially did the same as Guava's Closeables#closeQuietly

http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/com/google/common/io/Closeables.html#closeQuietly(java.io.Closeable)

Incidentally, I noticed that when I use Lombok-PG then my @Cleanup uses result in IOExceptions, whereas Lombok doesn't do this.

Ideally, I'd like to ignore the IOException from close, but log it if 'Logger log' exists in the scope.

**Comment by peichhorn** [comment]
Thank you for your feedback. I will look into it.

**Comment by peichhorn** [comment]
I'm going with Roel's comment in [issue 388](http://code.google.com/p/projectlombok/issues/detail?id=388#c1) that you should never ignore the IOException when calling `close()` on a writable resource. I'm however fine with an `quiet` option, that is turned off by default.

**Comment by fommil** [comment]
OK thanks, I would only use the quiet option on a reader anyway.

**Comment by peichhorn** [comment]
Done.. I've also deployed a new SNAPSHOT release, which you may find here: [link](https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/0.11.2-SNAPSHOT)
