### ISSUE TITLE
@VetoableChangeListenerSupport

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#94]
I posted an RFE on the Lombok mailing list and it was suggested I repeat it here

https://groups.google.com/forum/?fromgroups#!topic/project-lombok/iBgTxxfHc8c

(somebody pointed out that you provide something to do @PropertyChangeSupported)

It would be really cool if something like the following

``` java
public @Data @PropertyChangeSupported @VetoableChangeSupported class Person {
    private String name;
}
```

produced the following (imports not included for brevity):

``` java
public class Person {
    // there are probably some obscure "has listener support" interfaces we're supposed to implement

    @Getter private String name;

    private final PropertyChangeSupport propListeners = new PropertyChangeSupport(this); // dubious passing of 'this'
    private final VetoableChangeSupport vetoListeners = new VetoableChangeSupport(this);

    public void addPropertyChangeListener(PropertyChangeListener listener) {
            propListeners.addPropertyChangeListener(listener);
        }

        public void removePropertyChangeListener(PropertyChangeListener listener) {
            propListeners.removePropertyChangeListener(listener);
        }

        public void addVetoableChangeListener(VetoableChangeListener listener) {
            vetoListeners.addVetoableChangeListener(listener);
        }

        public void removeVetoableChangeListener(VetoableChangeListener listener) {
            vetoListeners.removeVetoableChangeListener(listener);
        }   

    public void setName(String name) {
        try {
            vetoListeners.fireVetoableChange("name", this.name, name);
        } catch (PropertyVetoException ex) {
            throw new IllegalArgumentException("name: " + name);
        }
        this.name = name;
        propListeners.firePropertyChange("name", this.name, name);
    }
}
```

**Comment by fommil** [comment]
(wtf with github's formatting of my message???)

EDIT: I've formatted it nicely for you.

**Comment by fommil** [comment]
UPDATE: the handling of a PropertyVetoException could be parameterised in the annotation. The two main options are: throw a runtime exception or (my favourite default) silently return without alerting any property listeners.

PS: SUN chose to send out a second message to all listeners if anything does a veto. It is worth reminding users of this in your annotation documentation. (although sensible when there are multiple veto listeners, it is often a pain to code for, so I ended up created an abstract listener which ignores "reset" messages when I know there is only one listener).

**Comment by peichhorn** [comment]
I will look into this.

**Comment by peichhorn** [comment]
Done. Still need to update the documentation, though.
