### ISSUE TITLE
@Cleanup for parameters

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#95]
Sometimes I want to be able to mark a method's parameter with @Cleanup, but this doesn't seem to be allowed.

The generated code should be exactly the same as if the parameter were defined on the first line of the method.

**Comment by peichhorn** [comment]
Done.. I've also deployed a new SNAPSHOT release, which you may find here: [link](https://oss.sonatype.org/content/repositories/snapshots/com/github/peichhorn/lombok-pg/0.11.2-SNAPSHOT)
