### ISSUE TITLE
@Builder should have a way to specify which fields are required

### ISSUE THREAD

**Issue by ttozser** [peichhorn/lombok-pg#97]
It is a really great feature of the builder that it doesn't allow the user to call the build method until all of its final field are set.
But I would like to be able to set non final fields to be required too. So the user can't forget to specify their value. 

I don't know which would be the best solution: 
- parameters in the `@Builder` annotation to include or exclude fields from required fields
- annotations on the fields to include/exclude them
  - with lombok specific annotations
  - using the jsr 303 NotNull annotation

**Comment by peichhorn** [comment]
Sounds good.

**Comment by ttozser** [comment]
I checked out the code and I found out that this is already implemented with jsr 305 `@Nonnull` annotation.

**Comment by ttozser** [comment]
Maybe the documentation should mention it.
