### ISSUE TITLE
Netbeans niceness

### ISSUE THREAD

**Issue by fommil** [peichhorn/lombok-pg#99]
This is more of a "heads up" to discussions between mainstream Lombok and Netbeans:

  http://netbeans.org/bugzilla/show_bug.cgi?id=215078

  http://code.google.com/p/projectlombok/issues/detail?id=393

so that lombok-pg features can hopefully stick to the requests of the Netbeans developers in order to ensure IDE compatibility.

**Comment by peichhorn** [comment]
Thanks for the heads up. The patch provided by Jan Lahoda looks really interesting. I'm definitely going to play around with this.

**Comment by fommil** [comment]
Awesome! I'll make sure the Netbeans team knows about this. Is there a maven repository for snapshot releases?

**Comment by peichhorn** [comment]
I will need to deploy a new snapshot once I get home from work.
You may find the snapshots here: [link](https://oss.sonatype.org/content/repositories/snapshots/)

**Comment by fommil** [comment]
Hi Philipp,

How would I do that in my pom.xml?

## 

Sam

**Comment by peichhorn** [comment]
by adding this to your `pm.xml`:

``` xml
<repositories>
  <repository>
    <id>sonatype-oss-repo-snapshots</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    <snapshots>
      <enabled>true</enabled>
    </snapshots>
  </repository>
</repositories>
```

**Comment by fommil** [comment]
ok, that seems to get the jars.

However, when I try either 0.11.1-SNAPSHOT or 0.11.2-SNAPSHOT (and a clean/build) all my Lombok classes in Netbeans have big error badges and it is as if the Lombok annotations are not being processed (e.g. getters/setters not created and log fields not there).

Compiles fine from the command line, though.

**Comment by peichhorn** [comment]
I'm on my way home and will try out the snapshots in a few minutes.
Which netbeans version are you using?

**Comment by peichhorn** [comment]
I've tested `@Data`, `@Getter`, `@Setter` and `@Log` with Netbeans 7.0.1 and Netbeans 7.2 RC1 and everything worked just fine.

**Comment by fommil** [comment]
7.2rc1

Kind regards,
Sam Halliday

##

**Comment by fommil** [comment]
Odd, are you using Maven projects?

Kind regards,
Sam Halliday

##

**Comment by peichhorn** [comment]
Oh, no I'm not.. that might be it.. gonna check real quick..

**Comment by peichhorn** [comment]
Works as a Maven project as well for me.

**Comment by fommil** [comment]
Ok, I shutdown NetBeans, cleared the cache (var folder) and restarted and it worked :-) 

Kind regards,
Sam Halliday

##

**Comment by fommil** [comment]
I am using your snapshot releases and I'm afraid to report that NetBeans refactoring is still breaking down when using Lombok annotations. e.g. refactor a classname or move to a different package when using typical annotations like @Log, @RequiredArgsConstructor, @ListenerSupport.

I would be happy to try and track down the offending annotations if you are able to help (including with standard Lombok annotations). Because of @ListenerSupport, I am now using Lombok PG instead of the canonical release.

**Comment by fommil** [comment]
I think it is also relevant to note that annotations on a class result in warnings at the class level being on the annotation line, and not the class definition line, in NetBeans. Guess: NetBeans is getting off-by-one errors at the source code level and then operations like warnings/errors/refactoring/parsing are all affected. I'm not knowledgeable enough to know if Jan's suggestions will address these types of problems.

**Comment by peichhorn** [comment]
> I am using your snapshot releases and I'm afraid to report that NetBeans refactoring is still breaking down when using Lombok annotations.

That's why this issue is still open. ;)

> I would be happy to try and track down the offending annotations if you are able to help (including with standard Lombok annotations). 

I'll take every feedback from you I can get and try to get all the features working well enough. I can't promise you anything though, since I've never looked in the netbeans code base. But I'm pretty sure, that we can still improve a lot of features with Jan's suggestions.
I'm not sure if you're aware of it, but I'm also a frequent committer to lombok, so working on the lombok "standard" annotations is not an issue.

**Comment by fommil** [comment]
Ok cool. I did some NetBeans contributions a few years ago, so I am relatively familiar with the Netbeans Java editor/hints APIs, but Jan is just the chap for the real details - all the business about synthetic trees was beyond my understanding. I don't understand which stage in the compile process Netbeans is using to build up its javac tree and how it then works out where that is physically in a source file that didn't directly generate it.

Is there a document that summarises how Lombok works when using the SUN javac?

I have a suspicion that if Lombok is actually clearing annotations from the compiled class files then that might be confusing the IDEs - it would be interesting to see what happens when the annotations are left there (causing no harm at runtime). One could certainly see that resulting in misalignments when calculating source code locations of tree elements.

What tests do you want me to make? I'd be happy to provide you with a Maven project that you could open in Netbeans and then go through a list of actions to see the failures in action. One of the most recurring problems seems to be that everything from "public class ..." to the top of the file is duplicated, resulting in invalid code. Happens with refactor and method creation hint, at least.

**Comment by peichhorn** [comment]
> I have a suspicion that if Lombok is actually clearing annotations from the compiled class files then that might be confusing the IDEs

Good point, lombok does exactly that. So first step would be not to remove the annotations when running in Netbeans IDE.

> What tests do you want me to make? I'd be happy to provide you with a Maven project that you could open in Netbeans and then go through a list of actions to see the failures in action. 

I think, that I have a fairly decent test project now. It would be nice, if I could get constant feedback from you, when I release new snapshots. Since it's possible that I accidentally miss a use-case.

**Comment by peichhorn** [comment]
I did a quick check, leaving the annotations untouched when running in Netbeans IDE, works great.
Also a lot of features of lombok-pg can be fixed by giving the field declarations the position of -1, since Netbeans recognizes the generated AST as synthetic then.

**Comment by peichhorn** [comment]
**Quick list, that I will update constantly...**
(you will always find it on the bottom of this discussion)

Features that work properly :
- `@AllArgsConstructor`, `@RequiredArgsConstructor` and `@NoArgsConstructor` - no brainer
- `@Cleanup` - fixed
- `@Delegate` - no brainer 
- `@EqualsAndHashcode` - no brainer 
- `@Getter` and `@Setter` - no brainer 
- `@Log` - fixed
- `@ToString` - fixed
- `@AutoGenMethodStub` - no brainer
- `@BoundPropertySupport`and `@BoundSetter` - fixed
- `@DoPrivileged` - fixed
- `@Builder` - fixed
- `@EnumId` - fixed
- `@LazyGetter` - fixed
- `@ListenerSupport` - fixed
- `@FluentSetter` - no brainer
- `@Sanitize.Normalize` and `@Sanitize.With` - fixed
- `@SwingInvokeLater` and `@SwingInvokeAndWait` - fixed
- `@Validate.NotEmpty`, `@Validate.NotNull` and `@Validate.With` - fixed
- `@VisibleForTesting` - no brainer
- `Application` and `JVMAgent` - no brainer

Features that still need some work:
- `@Getter(lazy=true)` - generate a normal getter
- `val` - no clue
- `@SneakyThrows` - no clue
- `@Synchronized` - was fixed, check again, there were some changes concerning the pos. info
- `yield(object)` - essentially fixed, but yield methods don't throw any checked exceptions, so we need to gobble the error message in netbeans..
- `@Action`  - remove method arguments that don't start with `_` and add them as local variables; replace return type
- `@Builder.Extension` - just create a method stub in the builder, don't remove the actual method..
- `@ExtensionMethod` - no clue
- `@Function` - remove method arguments that don't start with `_` and add them as local variables; replace return type
- `@WriteLock` and `@ReadLock` - only add lock field
- `@Await`, `@Signal` and `@AwaitBeforeAndSignalAfter` -  only add lock and condition field
- `@Predicate` - remove method arguments that don't start with `_` and add them as local variables; replace return type
- `@Rethrow` and `@Rethrows` - handle similar to `@Sneakythrows`
- `@Singleton` - just generate `getInstance()` method
- `tuple(expr1, expr2, ...)` - no clue

Even for the features that "work", there are certain scenarios were the last line of the file will still be removed when you refactor or when you insert code. I still need to investigate this.

**Comment by fommil** [comment]
Try changing Blah to Bloo in the following, refactor is cancelled by the editor.

``` java
@lombok.ListenerSupport(TestRefactor.MyListener.class)
public class TestRefactor {

    public enum Blah {
    }

    public interface MyListener {

        public void doBlah(Blah blah);
    }
}
```

In addition, this code probably won't compile for you with javac because the package line is missing. (Ignore original version of this comment, I was using an earlier version, the refactor with the parameter removed works OK now)

**Comment by fommil** [comment]
Netbeans refactor "create method doOtherStuff" results in the trailing } being dropped from the file. (I'm also seeing something similar to this in a much bigger class, where that multiple paste nonsense happens again. But I can't isolate it with a test case).

Bizarrely, this works fine if I use a full class path of both the lombok annotation and the listener interface.

``` java

package test;

import lombok.ListenerSupport;
import test.TestNewMethod.MyListener;

@ListenerSupport({MyListener.class})
public class TestNewMethod {

    public interface MyListener {
        public void stuff();
    }

    public void doStuff() {
        doOtherStuff();
    }
}
```

**Comment by fommil** [comment]
This is probably a dupe of the above from 8 days ago (but now testing with 21st July snapshot), this breaks with missing closing brace when attempting to create the field.

``` java
package test;

import javax.swing.event.ChangeListener;
import lombok.ListenerSupport;

@ListenerSupport(ChangeListener.class)
public class TestInsertField {

    private void method() {
        String value = FIELD_TO_CREATE;
    }
}
```

**Comment by peichhorn** [comment]
Thanks for letting me know. I will look into it.
